# $Id: makefile 72988 2015-08-06 22:35:27Z cxh $
# The name of the FMU to be built.
FMU_NAME = ZeroCrossingDetectorIT

# The rules are in a separate file so that we can easily update them.
include fmu.mk
