/* Generated By:JavaScope: Do not edit this line. JavaScope.java */
/* Test out the output from JavaScope, which tends to put $ everywhere

 Copyright (c) 2000-2001 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS.

                                        PT_COPYRIGHT_VERSION_2
                                        COPYRIGHTENDKEY
@ProposedRating Red (cxh@eecs.berkeley.edu)
@AcceptedRating Red (cxh@eecs.berkeley.edu)
*/

package ptolemy.lang.java.test; import COM.sun.suntest.javascope.database.js$;import COM.sun.suntest.javascope.database.CoverageUnit; 
//////////////////////////////////////////////////////////////////////////
//// JavaScope

/** Test out the output from JavaScope, which tends to put $ everywhere

@author Jeff Tsay, Christopher Hylands
@version $Id$
*/
public class JavaScope { static private int js$t0 = js$.setDatabase("/home/eecs/cxh/jsdatabase");static private String[] js$p={"ptolemy","lang","java","test",};static private CoverageUnit js$c=js$.c(js$p,"JavaScope","/export/maury/maury2/cxh/src/ptII/ptolemy/lang/java/test/jsoriginal/JavaScope.java",4869L,js$n());  static final int[] js$a = js$c.counters; 
    public JavaScope() { js$.g(JavaScope.js$a,1); 
     js$.g(JavaScope.js$a,0);/*$js$*/ }
    public int anInteger = 1; static private int js$n() {return 2;} 
}
