#!/bin/sh
# $Id$
# Script to convert codegen code targeted for c to java
for file in $@
do
	sed -e 's/ptolemy.codegen.c/ptolemy.codegen.java/g' \
	    -e 's/CCode/JavaCode/g' \
	    -e 's/CParse/JavaParse/g' \
	    -e 's/TYPE_Int/TYPE_Integer/g' \
	    -e 's/Intto/Integerto/g' \
	    -e 's/toInt(/toInteger/g' \
	    $file > /tmp/fixjavacode
	diff $file /tmp/fixjavacode
	cp /tmp/fixjavacode $file 
done
