#!/bin/sh
# $Id$
# Script that gets the contents of
# https://accessors.org/wiki/Version0/OptionalJavaScriptModules?action=markdown -O OptionalJavaScriptModules.md
# using cookies and wget and concatenates it with $PTII/doc/jsdoc/topREADMEEnd.md to create $PTII/doc/jsdoc/topREADME.md

cd $PTII/doc/jsdoc

tmpfile=/tmp/makeptjsdocREADME.tmp

echo "$0: Attempting to get OptionalJavaScriptModules.md from the accessors wiki"

wget --no-check-certificate https://accessors.org/wiki/Version0/OptionalJavaScriptModules?action=markdown -O $tmpfile  2>&1 >/dev/null | grep https://www.terraswarm.org/login/?denied >& /dev/null

status=$?

# If access was not denied, then move what was downloaded to OptionalJavaScriptModules.md
if [ $status -eq 1 ]; then
    echo "$0: Successfully downloaded OptionalJavaScriptModules.md"
    echo "$0: Updating `pwd`/OptionalJavaScriptModules.md"
    mv $tmpfile OptionalJavaScriptModules.md
else
    echo "$0: Could not get OptionalJavaScriptModules.md.  Using the default version."
fi

echo "$0: Creating `pwd`/topREADME.md"
cat OptionalJavaScriptModules.md topREADMEEnd.md > topREADME.md


    
