#!/bin/sh

actors=`grep AcceptedRating *.java | grep Green | awk -F: '{print $1}' | sed 's/.java//'`
for actor in $actors
do
    grep $actor *.xml > /dev/null
    status=$?
    if [ $status = 1 ]; then
	echo "Green actor $actor not found in xml files"
    fi
done