# Test DepthFirstTransformer.
#
# @Author: Thomas Huining Feng
#
# @Version: $Id$
#
# @Copyright (c) 1997-2007 The Regents of the University of California.
# All rights reserved.
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
#
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
#                       PT_COPYRIGHT_VERSION_2
#                       COPYRIGHTENDKEY
#######################################################################

# Ptolemy II test bed, see $PTII/doc/coding/testing.html for more information.

# Load up the test definitions.
if {[string compare test [info procs test]] == 1} then {
    source testDefs.tcl
} {}

######################################################################
####
#
test XMLTest-4.1.1 {Test rule4.xml with host4_1.xml} {
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_1.xml]
    [$matchResult getMatchResult] toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.gui.Display {.host4.Display2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.1.2 {Test rule4.xml with host4_1.xml (all matches)} {
    set helper [java::new ptolemy.actor.gt.test.AllMatchingTestHelper]
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_1.xml [java::field $helper callback]]
    $helper toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.gui.Display {.host4.Display2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.2.1 {Test rule4.xml with host4_2.xml} {
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_2.xml]
    [$matchResult getMatchResult] toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display2.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display2}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.2.2 {Test rule4.xml with host4_2.xml (all matches)} {
    set helper [java::new ptolemy.actor.gt.test.AllMatchingTestHelper]
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_2.xml [java::field $helper callback]]
    $helper toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display2.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display2}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.3.1 {Test rule4.xml with host4_3.xml} {
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_3.xml]
    [$matchResult getMatchResult] toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.3.2 {Test rule4.xml with host4_3.xml (all matches)} {
    set helper [java::new ptolemy.actor.gt.test.AllMatchingTestHelper]
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_3.xml [java::field $helper callback]]
    $helper toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.4.1 {Test rule4.xml with host4_4.xml} {
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_4.xml]
    [$matchResult getMatchResult] toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.4.2 {Test rule4.xml with host4_4.xml (all matches)} {
    set helper [java::new ptolemy.actor.gt.test.AllMatchingTestHelper]
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_4.xml [java::field $helper callback]]
    $helper toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.5.1 {Test rule4.xml with host4_5.xml} {
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_5.xml]
    [$matchResult getMatchResult] toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.5.2 {Test rule4.xml with host4_5.xml (all matches)} {
    set helper [java::new ptolemy.actor.gt.test.AllMatchingTestHelper]
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_5.xml [java::field $helper callback]]
    $helper toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.6.1 {Test rule4.xml with host4_6.xml} {
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_6.xml]
    [$matchResult getMatchResult] toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}

test XMLTest-4.6.2 {Test rule4.xml with host4_6.xml (all matches)} {
    set helper [java::new ptolemy.actor.gt.test.AllMatchingTestHelper]
    set matchResult [java::call ptolemy.actor.gt.GraphMatcher match rule4.xml host4_6.xml [java::field $helper callback]]
    $helper toString
} {{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}
{ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion1} = ptolemy.actor.TypedIOPort {.host4.Const.output3}, ptolemy.actor.TypedIOPort {.rule4.Pattern.A.criterion2} = ptolemy.actor.TypedIOPort {.host4.Const.output2}, ptolemy.actor.TypedIOPort {.rule4.Pattern.B.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue3.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion1} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.input}, ptolemy.actor.TypedIOPort {.rule4.Pattern.C.criterion2} = ptolemy.actor.TypedIOPort {.host4.AbsoluteValue2.output}, ptolemy.actor.TypedIOPort {.rule4.Pattern.D.criterion1} = ptolemy.actor.TypedIOPort {.host4.Display3.input}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.A} = ptolemy.actor.lib.Const {.host4.Const}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.B} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue3}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.C} = ptolemy.actor.lib.AbsoluteValue {.host4.AbsoluteValue2}, ptolemy.actor.gt.AtomicActorMatcher {.rule4.Pattern.D} = ptolemy.actor.lib.gui.Display {.host4.Display3}, ptolemy.actor.gt.Pattern {.rule4.Pattern} = ptolemy.actor.TypedCompositeActor {.host4}}}
