ME =		ptolemy/plot/img

DIRS = 		

# Root of the Ptolemy II directory
ROOT =		../../..

CLASSPATH =	$(ROOT)

# Get configuration info
CONFIG =	$(ROOT)/mk/ptII.mk
include $(CONFIG)

JSRCS = 

EXTRA_SRCS = \
	fill.gif \
	format.gif \
	print.gif \
	reset.gif

all: 


# Get the rest of the rules
include $(ROOT)/mk/ptcommon.mk