#!/bin/sh
# $Id$
# A script that updates the DOPCenter.png file
# This script will only work on a machine that
# has a graphica display.
# Linux machines without physical graphical displays
# can use Xvfb
# 1. Install Xvfb on your machine
#    yum install Xvfb 
# 2. Start up the display
#    Xvfb :1 -screen 0 1024x768x24 &
#    export DISPLAY=localhost:1.0
# 3. Run this script
#    $PTII/ptolemy/domains/space/demo/DOPCenter/updateDOPCenterImage
# Local admins, see also:
# http://embedded.eecs.berkeley.edu/dopsysadmin/faq/125.html

# This model requires that ~/.spacecadet contains the password.

# Use a png because there is already a .gif that is the background.
# Note that png does not reliably display under Windows XP or Windows Server 2003.

$PTII/bin/ptinvoke ptolemy.vergil.basic.ExportImage png -run $PTII/ptolemy/domains/space/demo/DOPCenter/DOPCenter.xml
#svn update -m "Automatic update" DOPCenter.gif