package ptolemy.actor.corba.util;

/**
 * ptolemy/actor/corba/util/CorbaActorHolder.java
 * Generated by the IDL-to-Java compiler (portable), version "3.0"
 * from CorbaActor.idl
 * Thursday, January 18, 2001 7:07:58 PM PST
 */

/* A CORBA compatible interface that implements the execution
 * methods of Ptolemy II.
 */
public final class CorbaActorHolder implements
org.omg.CORBA.portable.Streamable {
    public ptolemy.actor.corba.util.CorbaActor value = null;

    public CorbaActorHolder() {
    }

    public CorbaActorHolder(ptolemy.actor.corba.util.CorbaActor initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = ptolemy.actor.corba.util.CorbaActorHelper.read(i);
    }

    @Override
    public void _write(org.omg.CORBA.portable.OutputStream o) {
        ptolemy.actor.corba.util.CorbaActorHelper.write(o, value);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return ptolemy.actor.corba.util.CorbaActorHelper.type();
    }
}
