#!/bin/sh -x
# $Id$

# Build models and run them.

# Clean up
rm *.out *.xml *.plt
rm -rf $HOME/cg/
# Build the models
$PTII/bin/ptjacl ModularCodeGenLarge.tcl

models="pubSubAggMCG_2_2-clean.xml
pubSubAggMCG_2_2.xml
pubSubAgg_2_2-clean.xml
pubSubAgg_2_2.xml
pubSubAggother_2_2-clean.xml
pubSubAggother_2_2.xml"

for model in $models
do
    echo $model
    $PTII/bin/ptjacl run.tcl $model
done

$PTII/bin/ptcg -language java -measureTime true pubSubAggMCG_2_2.xml
