#!/bin/sh
# $Id$
# A script that reads in the output of MoMLSimpleStatistical
# application and generates a PlotML suitable for use with
# $PTII/bin/ptplot

cat << EoF
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE plot PUBLIC "-//UC Berkeley//DTD PlotML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/PlotML_1.dtd">
<plot>
<!-- Ptolemy plot, version 5.7.1.devel , PlotML format. -->
<title>Number of actors vs time and memory</title>
<xLabel>Number of actors</xLabel>
<yLabel>Time in ms, Memory in 10k Bytes</yLabel>
	<default marks="bigdots"/>}

EoF

echo '<dataset name="Open time (ms.)">'
for file in $@
do 
   basename=`basename $file`
   size=`echo $basename | sed 's/pubsub//' | sed 's/.out//'`
   egrep "^Opened" $file | awk -v size=$size ' {
	print "<p x=\"" size * 5 "\" y=\"" $3 "\"/>"
     }'
done
echo "</dataset>"

echo '<dataset name="Preinitialize time (ms.)">'
for file in $@
do 
   basename=`basename $file`
   size=`echo $basename | sed 's/pubsub//' | sed 's/.out//'`
   egrep "^preinitialize" $file | awk -v size=$size ' {
	print "<p x=\"" size * 5 "\" y=\"" $3 "\"/>"
     }'
done
echo "</dataset>"

echo '<dataset name="Preinit + Init time (ms.)">'
for file in $@
do 
   basename=`basename $file`
   size=`echo $basename | sed 's/pubsub//' | sed 's/.out//'`
   egrep "^Manager.initialize" $file | awk -v size=$size ' {
	print "<p x=\"" size * 5 "\" y=\"" $3 "\"/>"
     }'
done
echo "</dataset>"

echo '<dataset name="Run time (ms.)">'
for file in $@
do 
   basename=`basename $file`
   size=`echo $basename | sed 's/pubsub//' | sed 's/.out//'`
   grep StatRT $file | awk -v size=$size ' {
	print "<p x=\"" size * 5 "\" y=\"" $1 "\"/>"
     }'
done
echo "</dataset>"

echo "<dataset name=\"Memory\">"
for file in $@
do 
   basename=`basename $file`
   size=`echo $basename | sed 's/pubsub//' | sed 's/.out//'`
   grep StatRT $file | awk -v size=$size ' {
   	mem = substr($4, 0, length($4)-1)
        free= substr($6, 0, length($6)-1)
	used = (mem-free)
	print "<p x=\"" size * 5 "\" y=\"" used "\"/>"
     }'
done
echo "</dataset>"
echo "</plot>"