#!/bin/sh
# $Id$
# A script that runs models using MoMLSimpleStatisticalApplication
# and saves the output in individual files

for file in $@
do
    echo $file
    logfile="`dirname $file`/`basename $file .xml`.out"
    time java -Xmx1600M -classpath "$PTII" \
    	 ptolemy.actor.gui.MoMLSimpleStatisticalApplication \
	 $file >& $logfile
done