#!/bin/sh
# $Id$
# A script that runs models using MoMLSimpleStatisticalApplication
# and saves the output in individual files

for file in $@
do
    logfile="`dirname $file`/`basename $file .xml`"
    java -Xmx1600M -classpath "$PTII" \
    	 ptolemy.actor.gui.MoMLSimpleStatisticalApplication \
	 $file 2>&1 $logfile
done