#!/bin/sh
# $Id$
# A script that will make a fmu directory
# Usage: mkfmudir fmuName

if [ $# -ne 1 ]; then
    echo "$0: Usage: $0 fmuName"
    echo " For example '$0 Foo'"
    exit 2
fi

fmuName=$1

if [ -d $fmuName ]; then
    echo "$0: cowardly exiting because $fmuName directory exists."
    exit 3
fi

mkdir $fmuName

fmiTemplateDirectory=$PTII/ptolemy/actor/lib/fmi/fmus/template
fmiVersion=fmiv20
fmiSourceDirectory=$fmiTemplateDirectory/$fmiVersion

if [ ! -d $fmiTemplateDirectory ]; then
    echo "$0: Could not find $fmiTemplateDirectory, exiting."
    exit 4
fi

if [ ! -d $fmiSourceDirectory ]; then
    echo "$0: Could not find $fmiSourceDirectory, exiting."
    exit 5
fi


YEAR=`date +%Y`

cat > $fmuName/makefile <<EOF

# Makefile for Java Ptolemy II Functional Mock-up Unit (FMU) $fmuName CoSimulation
#
# @Author: Christopher Brooks (makefile only)
#
# @Version: $Id: makefile 69601 2014-07-30 13:51:01Z cxh $
#
# @Copyright (c) $YEAR The Regents of the University of California.
# All rights reserved.
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
#
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY

FMU_NAME = $fmuName

include ../fmus.mk

EOF

mkdir $fmuName/src

#cp $fmiTemplateDirectory/model.png $fmuName/src

mkdir $fmuName/src/binaries

mkdir $fmuName/src/documentation
cat > $fmuName/src/documentation/_main.html <<EOF2
<html>
<head>
    <title>Documentation for $fmuName.fmu</title>
<style type="text/css">
  html { font-family: Verdana, Arial, Helvetica, sans-serif; }
  h1   { color: #000066; }
</style>
</head>
<body>
<h1>$fmuName.fmu</h1>
The $fmuNamel implements the following equation: 
<ul>
<li> TBD</li>
</ul>
with start values TBD
<ul>
<li>TBD: TBD
</ul>

<br>

The above description refers to the variables used 
in file <code>$fmuName.c</code>.

</body>
</html>

EOF2

cat > $fmuName/src/modelDescription.xml <<EOF3
<?xml version="1.0" encoding="ISO-8859-1"?>
<fmiModelDescription
  description="TBD"
  fmiVersion="2.0"
  guid="{0e634258-412b-4602-a29d-e7882503fd59}"
  modelName="$fmuName"
  numberOfEventIndicators="42"
   >
    
  <CoSimulation
    modelIdentifier="stairsA"
    canHandleVariableCommunicationStepSize="true"
    canHandleEvents="true"
    canProvideMaxStepSize="true"/>
    
<ModelVariables>
  <ScalarVariable
     name="level"
     valueReference="0"
     description="level"
     causality="output">
    <Real/>
  </ScalarVariable>
</ModelVariables>
</fmiModelDescription>

EOF3

mkdir $fmuName/src/sources

cp $fmiTemplateDirectory/sources/{build_fmu,build_fmu.bat,fmu.mk} $fmuName/src/sources
cp $fmiTemplateDirectory/sources/fmuTemplate_$fmiVersion.c $fmuName/src/sources/fmuTemplate.c
cp $fmiTemplateDirectory/sources/fmuTemplate_$fmiVersion.h $fmuName/src/sources/fmuTemplate.h
cp $fmiSourceDirectory/{fmi2FunctionTypes.h,fmi2Functions.h,fmi2TypesPlatform.h} $fmuName/src/sources

cat > $fmuName/src/sources/makefile <<EOF4
# $Id$
# The name of the FMU to be built.
FMU_NAME = $fmuName

# The rules are in a separate file so that we can easily update them.
include fmu.mk
EOF4


