#!/bin/sh
# $Id: mkfmudir 70377 2014-10-21 22:32:43Z cxh $
# A script that will make a fmu-1.0 directory
# Usage: mkfmudir fmuName

if [ $# -ne 1 ]; then
    echo "$0: Usage: $0 fmuName"
    echo " For example '$0 Foo'"
    exit 2
fi


fmuName=$1

if [ -d $fmuName ]; then
    echo "$0: cowardly exiting because $fmuName directory exists."
    exit 3
fi


mkdir $fmuName

fmiTemplateDirectory=$PTII/ptolemy/actor/lib/fmi/fmus/template
if [ ! -d $fmiTemplateDirectory ]; then
    echo "$0: Could not find $fmiTemplateDirectory, exiting."
    exit 4
fi

fmuBase=`baseName $fmuName ME1`
fmusdk2Directory=$HOME/src/fmi/fmusdk2/fmu10/src/models/$fmuBase

if [ ! -d $fmusdk2Directory ]; then
    echo "$0: Could not find $fmusdk2Directory, exiting."
    exit 4
fi

fmiVersion=fmiv10
#fmiSourceDirectory=$fmiTemplateDirectory/$fmiVersion

case $fmuName in
    *ME1) fmiSourceDirectory=$HOME/src/fmi/fmusdk2/fmu10/src/model_exchange/include
         csOrMe=Me
         ;;
    *)   fmiSourceDirectory=$HOME/src/fmi/fmusdk2/fmu10/src/co_simulation/include
         csOrMe=Cs
         ;;
esac          

if [ ! -d $fmiSourceDirectory ]; then
    echo "$0: Could not find $fmiSourceDirectory, exiting."
    exit 5
fi


YEAR=`date +%Y`
GUID=`uuidgen`

cat > $fmuName/makefile <<EOF

# Makefile for Java Ptolemy II Functional Mock-up Unit (FMU) $fmuName CoSimulation
#
# @Author: Christopher Brooks (makefile only)
#
# @Version: $Id: mkfmudir 70377 2014-10-21 22:32:43Z cxh $
#
# @Copyright (c) $YEAR The Regents of the University of California.
# All rights reserved.
#
# Permission is hereby granted, without written agreement and without
# license or royalty fees, to use, copy, modify, and distribute this
# software and its documentation for any purpose, provided that the
# above copyright notice and the following two paragraphs appear in all
# copies of this software.
#
# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.
#
# 						PT_COPYRIGHT_VERSION_2
# 						COPYRIGHTENDKEY

FMU_NAME = $fmuName

include ../fmus.mk

EOF

mkdir $fmuName/src

cp $fmusdk2Directory/model.png $fmuName/src

mkdir $fmuName/src/binaries

mkdir $fmuName/src/documentation

cp $fmusdk2Directory/_main.html $fmuName/src/documentation/
cp $fmusdk2Directory/*.png $fmuName/src/documentation/
rm $fmuName/src/documentation/model.png

mkdir $fmuName/src/sources

sed "s/$fmuBase/$fmuName/" $fmusdk2Directory/$fmuBase.c > $fmuName/src/sources/${fmuName}.c
sed "s/$fmuBase/$fmuName/" $fmusdk2Directory/modelDescription.xml > $fmuName/src/modelDescription.xml

#cp $fmiTemplateDirectory/sources/{build_fmu,build_fmu.bat,fmu.mk} $fmuName/src/sources
if [ $csOrMe = "Cs" ]; then
    cp $fmiTemplateDirectory/sources/{build_fmu,build_fmu.bat,fmu.mk} $fmuName/src/sources
else
    cp $fmiTemplateDirectory/sources/fmu.mk $fmuName/src/sources
    sed -e 's/\(include="-DFMI_COSIMULATION -I."\)/# \1/' \
        -e 's/\(#include="-I."\)/#\1/' \
        < $fmiTemplateDirectory/sources/build_fmu > $fmuName/src/sources/build_fmu
    sed -e 's@/DFMI_COSIMULATION@@' \
        -e 's/Co-Simulation/Model Exchange/' \
        < $fmiTemplateDirectory/sources/build_fmu.bat > $fmuName/src/sources/build_fmu.bat
fi

cp $fmiTemplateDirectory/sources/fmuTemplate_$fmiVersion.c $fmuName/src/sources/fmuTemplate.c
cp $fmiTemplateDirectory/sources/fmuTemplate_$fmiVersion.h $fmuName/src/sources/fmuTemplate.h

cp $fmiSourceDirectory/*.h $fmuName/src/sources

cat > $fmuName/src/sources/makefile <<EOF4
# $Id: mkfmudir 70377 2014-10-21 22:32:43Z cxh $
# The name of the FMU to be built.
FMU_NAME = $fmuName

# The rules are in a separate file so that we can easily update them.
include fmu.mk
EOF4


