#!/bin/sh

#rm -rf repos cvs_chess tmp.svn
#egrep  '^\$PTII' allchesscvs | awk '{print "rm -rf {repos,cvs_chess,tmp.svn}/" $NF}' > /tmp/l

# Redo ActorBook, there were permissions problems.
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ActorBook
# StreaMorph is Empty
##$PTII/adm/cvs2svn/cvsTosvn cvs_chess StreaMorph
# StreamMapping is Empty
##$PTII/adm/cvs2svn/cvsTosvn cvs_chess StreamMapping
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess actionwebs
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess agv
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess apesless
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess apon
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess automotive
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess bhc
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess bipeds
# Redo car, there were eps files
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess car
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess certafcs
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess cg
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess chessadmin
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess chessannual
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess chesswww
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess clotho
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess cps
# Redo cpsatc because of permission problems.
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess cpsatc
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess cpslab
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess croquet
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess curriculum
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess dataflow
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess design
# Redo dgc because of permission problems.
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess dgc
# Redo dgc3 because of permission problems.
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess dgc3
# Empty $PTII/adm/cvs2svn/cvsTosvn cvs_chess dgc3admin
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess dgc3course
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess dgc3src
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess directors
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess drosonetsim
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess dsc
# Redo ee124 because of permission problems.
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ee124
# Redo eecs124 because of permission problems.
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess eecs124
# Does not exist $PTII/adm/cvs2svn/cvsTosvn cvs_chess eecs129

# Checked with diff
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess eecs149

#$PTII/adm/cvs2svn/cvsTosvn cvs_chess eecs149lab
# Diff issues
# Redoing now
# Some diffs in eps, move on.
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess eecs20
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess escher
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess gsoc
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess handsimdroid
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess hcddes
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess hcssas
# Redo hilv because of encoding
# Redo because of -kb
# Still one file, but move on
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess hilv
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess hsbc
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess hybrid
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess hyper
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess iab
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess icyphy
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ieee1588
# Redo because of Thermocouple_circuit.svg
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess instructors
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess itr
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess kepler
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess mast
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess modelica
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess mpc
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess muri
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess naomi
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess nes
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess nsferc
# Some pdf files
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess nsfpire
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess outreach
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess pa
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess presenters
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess pret
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess props
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess pss
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ptalon
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ptango
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ptdb
# Redo ptesdf because of lock file
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ptesdf
# Redo ptexternal because of lock file
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ptexternal
# Redo pthomas because of lock file
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess pthomas
# Redo ptides because of bogus name:
#PtidyOS\x7f\x7f\x7fTimeTriggeredTBD.c,v' would result in an illegal SVN filename: Subversion does not allow character '\x7f' in filename 'PtidyOS\x7f\x7f\x7fTimeTriggeredTBD.c'.
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ptides
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ptidesarch
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess ptolemy
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess reactable
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess reap
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess rss
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess scas
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess scos
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess scs
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess softdevel
# Redo because of eps
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess softwalls
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess starmac
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess stheeprojects
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess studygroup
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess superb
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess swisp
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess tbd
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess tcl
##$PTII/adm/cvs2svn/cvsTosvn cvs_chess tmp
##$PTII/adm/cvs2svn/cvsTosvn cvs_chess tobesaved
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess triq
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess trust
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess vw
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess webmaster
#$PTII/adm/cvs2svn/cvsTosvn cvs_chess western_jup

# To generate a script to create update the repos on repo.eecs
# egrep '^#\$PTII' allchesscvs | awk '{print "$PTII/adm/cvs2svn/syncit cvs_chess " $NF}' > /tmp/doit

# To generate a script that will check out the repos on moog.
# Run this as the vc user
# egrep '^#\$PTII' allchesscvs | awk '{print "svn co https://repo.eecs.berkeley.edu/svn/projects/chess/" $NF "/trunk/" $NF}'
