#!/bin/sh

#rm -rf repos cvs_embedded tmp.svn
# Ignore Empty $PTII/adm/cvs2svn/cvsTosvn cvs_embedded abpd
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded apbd
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded asves
# Ignore Empty $PTII/adm/cvs2svn/cvsTosvn cvs_embedded asvpapers
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded bear
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded blast
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded bogusgroup
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded buildmaster
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded caltrop
# Done$PTII/adm/cvs2svn/cvsTosvn cvs_embedded cases
# Done Almost empty $PTII/adm/cvs2svn/cvsTosvn cvs_embedded compaan
# Done Had a release/ directory $PTII/adm/cvs2svn/cvsTosvn cvs_embedded compose
$PTII/adm/cvs2svn/cvsTosvn cvs_embedded concurrency
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded cosi
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded dif
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded diva
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded dopcenter
# Done, not on the website $PTII/adm/cvs2svn/cvsTosvn cvs_embedded dopfpd
# Done, not on the website $PTII/adm/cvs2svn/cvsTosvn cvs_embedded dopseating
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded dopsysadmin
# Done $PTII/adm/cvs2svn/cvsTosvn cvs_embedded eecsx44
# $PTII/adm/cvs2svn/cvsTosvn cvs_embedded elab
$PTII/adm/cvs2svn/cvsTosvn cvs_embedded embeddedwww
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded giotto
# Done, no directory on website. $PTII/adm/cvs2svn/cvsTosvn cvs_embedded healtheu
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded hyinfo
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded inactive
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded m2t2
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded mescal
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded metropolis
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded mica
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded mobies
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded mocha
# Done, no directory on website $PTII/adm/cvs2svn/cvsTosvn cvs_embedded mocpaper
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded msgadmin
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded murieh
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded mvsis
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded platform
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded recons
# Ignore Empty $PTII/adm/cvs2svn/cvsTosvn cvs_embedded sec
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded smartnets
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded systems
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded tsrc
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded video
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded webmaster
#$PTII/adm/cvs2svn/cvsTosvn cvs_embedded wow

