#!/bin/sh

#rm -rf repos cvs_gsrc tmp.svn

$PTII/adm/cvs2svn/cvsTosvn cvs_gsrc javapages
$PTII/adm/cvs2svn/cvsTosvn cvs_gsrc mysql
$PTII/adm/cvs2svn/cvsTosvn cvs_gsrc php


# To generate a script to create update the repos on repo.eecs
# egrep '^#\$PTII' allchesscvs | awk '{print "$PTII/adm/cvs2svn/syncit cvs_chess " $NF}' > /tmp/doit

# To generate a script that will check out the repos on moog.
# egrep '^#\$PTII' allchesscvs | awk '{print "svn co https://repo.eecs.berkeley.edu/svn/projects/chess/" $NF "/trunk/" $NF}'
