#!/bin/sh

awk -F / '{
     if (last == "") {
         last = $1
     }
     if ($1 != last) {
         print "(cd " last "; cvs commit -m \"Added -kb\"; cvs update)"
         last = $1

     }
     filenames = filenames " " $2 "/"
     for(i=3;i<NF;i++) {
        filenames=filenames $i "/"
     }
     filenames = filenames $NF
     print "(cd " last "; cvs admin -kb " filenames ")"
     filenames=""    

 }
END {
	 print "(cd " last "; cvs admin -kb " filenames ")"
         print "(cd " last "; cvs commit -m \"Added -kb\"; cvs update)"
}
' /tmp/ufb2
