#!/bin/sh
# $Id$
# Simple conversions to dava output
awk '{if ($0 ~ /public Main()/) {
    	    if ($0 !~ /throws IllegalActionException, NameDuplicationException/) {
	       print $0, "throws IllegalActionException, NameDuplicationException"
            } else {
	       print $0
            }
        } else {
            print $0
        }
    }' $1 |
awk '{ if ($0 ~ /^package/) {
            print $0
            printf("\n");
            print "import ptolemy.kernel.util.IllegalActionException;"
            print "import ptolemy.kernel.util.NameDuplicationException;"
        } else {
            print $0
        }
    }' |
sed -e 's/\(ptolemy.data.type.BaseType\)\$\([A-Za-z]\)/\1.\2/g' \
    -e 's/append(null)/append("")/g' 
xs