# $Id$
# The name of the FMU to be built.
FMU_NAME = Linsys

CFLAGS = -I/opt/openmodelica/include -llapack -lblas -lgfortran 


# The rules are in a separate file so that we can easily update them.
include fmu.mk
