#!/bin/sh
# Find missing demos
# $Id$
# 1) Get all the demos from ptolemy/configs/doc/models.txt
# 2) For each demo/ directory in models.txt, look for .xml files that are not listed
#

cd $PTII

exitCode=0

verbose=no
if [ "$1" = "-v" ]; then
    verbose=yes
fi



modelsFile=$PTII/ptolemy/configs/doc/models.txt
demos1=/tmp/missingDemos.demos1.$$
cat $modelsFile | grep /demo/ | awk -F / '{for (i=2;i<=NF;i++) {printf("%s/", $i); if ($i ~ /demo/) {printf("\n"); break}}}' | sed 's@demo/$@demo@' | sort | uniq > $demos1
   

# Look for demo directories that are not listed in completeDemos
demos2=/tmp/missingDemos.demos2.$$
(cd $PTII; find . -name demo -type d | egrep -v '(adm|reports|signed|vendors)' | sed 's@^\./@@' | sed 's@demo/$@demo@' | sort ) | egrep -v '(com/microstar/xml/demo|diva/canvas/demo|doc/codeDoc/.*/demo|doc/doccheck/diva/canvas/demo|org/terraswarm/gdp/src/gdp.*/demo|ptolemy/apps|ptolemy/actor/lib/jjs/modules/contextAwareTest/demo)' > $demos2

if [ $verbose = "yes" ]; then 
    echo "### Demo directories that are not listed in $PTII/ptolemy/configs/doc/completeDemos.htm"
fi

demos3=/tmp/missingDemos.demos3.$$
comm -3 $demos1 $demos2 | awk '{print $1}' > $demos3

for demo in `cat $demos3`
do
    grep "<!--.*$demo" $PTII/ptolemy/configs/doc/completeDemos.htm >& /dev/null
    status=$?
    if [ $status -eq 1 ]; then
        echo "The $demo directory is not found in completeDemo.htm" >&2
        echo "    <!-- ../../../$demo -->" >&2
        exitCode=2
    fi        
done

# Script that prints out html for the demos.
# $demos is the list of .xml files for which we are to print demos.
function demoHTML {
    if [ $1 = "yes" ]; then 
        if [ ! -z "$2" ]; then
            foundDemo=no
            shift
            for demo in $@
            do                 
                demoDirectory=`dirname $demo`
                demoName=`basename $demoDirectory`
                #if [ $demo = "$demoDirectory/$demoName.xml" ]; then
                   echo "      <li>&2<a href=\"../../../$demo\">&2$demoName</a>&2(New in Ptolemy II 11.0)</li>&2" >&2
                   echo "or" >&2
                   echo "      <!-- ../../../$demo -->&2" >&2
                   exitCode=3
                   foundDemo=yes
                #fi
            done
            if [ $foundDemo = "no" ]; then
                echo "      <!-- Did not find demo with the same name as the directory? -->&2" >&2
                exitCode=4
            fi
        fi
    fi
}

if [ $verbose = "yes" ]; then 
    demoDirectories=`comm -3 $demos1 $demos2 | awk '{print $1}'`
    for demoDirectory in $demoDirectories
    do
        echo "#" $demoDirectory                     
        dirname=`dirname $demoDirectory`
        package=`basename $dirname`
        demos=`ls $demoDirectory/*/*.xml`

        if [ -z "$demos" ]; then
            echo "$demoDirectory contains no subdirectories with models." >&2
            exitCode=5
            continue;
        fi

        # For each demo in the directory, check to see if
        # it appears in completeDemos.htm as a commented out demo
        # If there is any demo that does not appear in
        # completeDemos as a commented out demo, then print
        # html for those demos

        missingDemos=""
        for demo in $demos
        do
            egrep "<!--.*$demo" $PTII/ptolemy/configs/doc/completeDemos.htm  >& /dev/null
            status=$?
            if [ $status -eq 1 ]; then
                egrep "$demo" $PTII/ptolemy/configs/doc/completeDemos.htm  | grep -v '<!--' >&2 /dev/null
                status=$?
                if [ $status -eq 1 ]; then
                    missingDemos="$missingDemos $demo"
                fi
            fi
        done

        if [ ! -z "$demos" -a -z "$missingDemos" ]; then
            echo "$demoDirectory contains demos that are in completeDemos.htm, but commented out." >&2
            exitCode=6
        else
            echo "demos: $demos, missingDemos: $missingDemos" >&2
            exitCode=7

            cat <<EOF

    <li>&2<a href="#$package">&2</a>&2</li>&2
...
    <h2>&2<a name="$package">&2</a>&2</h2>&2
    <ul>&2<!-- Alphabetical Please -->&2
EOF

            demoHTML $verbose "$missingDemos"
            echo "    </ul>&2" >&2
        fi
    done    
fi

if [ $verbose = "yes" ]; then 
    echo "### Look for .xml files that are in directories listed in completeDemos,"
    echo "###  but not the .xml file itself is not listed."
fi

modelsInModelsFile=/tmp/missingDemos.modelsInModelsFile.$$
modelsInDemoDirectory=/tmp/missingDemos.modelsInDemoDirectory.$$
for demoDirectory in `cat $demos1`
do
    if [ $verbose = "yes" ]; then 
        echo "## Checking $demoDirectory"
    fi
    individualDemoDirectories=`find $demoDirectory -mindepth 1 -maxdepth 1 -type d | grep -v .svn`
    for individualDemoDirectory in $individualDemoDirectories
    do                                   
        demoName=`basename $individualDemoDirectory`
        demoModel=`echo "$individualDemoDirectory/$demoName.xml" | sed "s@$PTII@@"`
        if [ ! -f "$PTII/$demoModel" ]; then
            # Check to see if it is commented out.
            grep "<!--" $PTII/ptolemy/configs/doc/completeDemos.htm | grep $demoModel >& /dev/null
            status=$?
            if [ $status -eq 1 ]; then
                grep -v "<!--" $PTII/ptolemy/configs/doc/completeDemos.htm | grep $demoModel >& /dev/null
                status=$?
                if [ $status -eq 1 ]; then
                    echo "$demoModel is not present" >&2
                    demoHTML $verbose $demoModel
                    exitCode=8
                fi
            fi
        fi

        grep $demoModel $modelsFile >& /dev/null
        status=$?
        if [ $status -eq 1 ]; then
            grep -v "<!--" $PTII/ptolemy/configs/doc/completeDemos.htm | grep $demoModel >& /dev/null
            status=$?
            if [ $status -eq 1 ]; then
                grep "<!--" $PTII/ptolemy/configs/doc/completeDemos.htm | grep $demoModel >& /dev/null
                status=$?
                if [ $status -eq 1 ]; then
                    echo "$demoModel is not present in completeDemos.htm" >&2
                    demoHTML $verbose $demoModel
                    exitCode=9
                fi
            else
                echo "Error: $demoModel is not present in $modelsFile, but is present in completeDemos.htm.  Maybe you need to run: (cd $PTII/ptolemy/configs/doc; make update)?" >&2
                exit 10
            fi
        fi           
    done
    # find $PTII/$demoDirectory -name "*.xml" | sed "s@$PTII/@@" >&2 $modelsInDemoDirectory
    # grep $demoDirectory $modelsFile | sed 's@\$CLASSPATH/@@' >&2 $modelsInModelsFile

    # comm -23 $modelsInDemoDirectory $modelsInModelsFile

    # if [ $verbose = "yes" ]; then 
    #     demos=`comm -23 $modelsInDemoDirectory $modelsInModelsFile | awk '{print $1}'`
    #     demoHTML
    # fi
done

rm -f /tmp/missingDemos.*

exit $exitCode
