#!/bin/sh
# Determine what codegen actors are used by the demos

models=`grep href demos.htm | grep ".xml" | awk -F \" '{print $2}'`
#echo $models
#for model in $models
#do
#    base=`basename $model .xml`
#    export JAVAFLAGS=-verbose
#    $PTII/bin/ptcg $model | grep "Loaded ptolemy.codegen" > $base.out
#done

classes=`cat *.out | sort | uniq -c | sort -nr | grep -v '\\$' | awk '{print $3}'`
for class in $classes
do 
	echo $class
	filename=$PTII/`echo $class | sed 's@\.@/@g'`.java
	grep "$class " *.out | awk -F . '{print "    " $1}' 
	egrep 'ProposedRating|AcceptedRating' $filename | awk '{print "    "$0}'

done