#!/bin/sh

rmic -classpath ${PTII}\;${PTII}/vendors/sun/jini/lib/jini-jspaces.jar ptolemy.domains.ct.demo.CarTracking.CarInformationSubscriber

rmic -classpath ${PTII}\;${PTII}/vendors/sun/jini/lib/jini-jspaces.jar ptolemy.domains.ct.demo.CarTracking.CTSubscriber

rmic -classpath ${PTII}\;${PTII}/vendors/sun/jini/lib/jini-jspaces.jar ptolemy.domains.ct.demo.CarTracking.DERealTimeSubscriber
