/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_Original
#define _Included_Original

void top8ms_offset0();
void top8ms_offset4();
void eventf();

#endif



