#!/bin/sh
# Check the copyright
#-[Mon May 24 22:21:34 1999 by cxh]-
year=`date +%Y`
for fullfile in $@
do
	copyright=`egrep Copyright $fullfile`
	status=$? 
	if [ $status -eq 1 ]; then
		echo "$fullfile does not contain a Copyright"
	else 
		echo "$copyright" | egrep -s $year
		status=$? 
		if [ $status -eq 1 ]; then
			echo "$fullfile is not Copyright $year"
			echo "    $fullfile: $copyright"
		fi
	fi
done 
