package ptolemy.domains.openmodelica.lib.omc.corba;

/**
 * OmcCommunication.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from omc_communication.idl
 * Thursday, October 27, 2005 10:11:20 AM CEST
 */

/* A CORBA compatible interface for omc.
 */
public interface OmcCommunication extends OmcCommunicationOperations,
org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface OmcCommunication
