package ptolemy.domains.openmodelica.lib.omc.corba;

/**
   OmcCommunicationHolder.java.
   Generated by the IDL-to-Java compiler (portable), version "3.2"
   from omc_communication.idl
   Thursday, October 27, 2005 10:11:20 AM CEST
  */
public final class OmcCommunicationHolder implements
        org.omg.CORBA.portable.Streamable {
    /** Construct an OmcCommunicationHolder object.
     */
    public OmcCommunicationHolder() {
    }

    /** Construct an OmcCommunicationHolder object.
     *  @param initialValue The OmcCommunication object.
     */
    public OmcCommunicationHolder(OmcCommunication initialValue) {
        value = initialValue;
    }

    ///////////////////////////////////////////////////////////////////
    ////                         public variables                  ////

    // Initialize value.
    public OmcCommunication value = null;

    ///////////////////////////////////////////////////////////////////
    ////                         public methods                    ////

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = OmcCommunicationHelper.read(i);
    }

    public org.omg.CORBA.TypeCode _type() {
        return OmcCommunicationHelper.type();
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        OmcCommunicationHelper.write(o, value);
    }

}
