package org.terraswarm.gdp;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * Structure used to manipulate the SO_LINGER option.<br>
 * <i>native declaration : /usr/include/bits/socket.h:4</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class linger extends Structure {
	/** Nonzero to linger on close. */
	public int l_onoff;
	/** Time to linger. */
	public int l_linger;
	public linger() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("l_onoff", "l_linger");
	}
	/**
	 * @param l_onoff Nonzero to linger on close.<br>
	 * @param l_linger Time to linger.
	 */
	public linger(int l_onoff, int l_linger) {
		super();
		this.l_onoff = l_onoff;
		this.l_linger = l_linger;
	}
	public linger(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends linger implements Structure.ByReference {
		
	};
	public static class ByValue extends linger implements Structure.ByValue {
		
	};
}
