#!/bin/sh
# $Id$
# A script that deploys a composite accessor to a remote machine.
#
# The steps are:
# 1. Create a directory on the remote machine
# 2. Use npm to install @terraswarm/accessors and any other modules on the remote machine
# 3. Create a small script to run the composite accessor on the remote machine
# 4. Copy the accessor to the remote machine
# 5. Invoke the accessor on the remote machine.

usage="$0: Usage: $0 remoteuser@remotehost compositeAccessor.js [-timeout timeoutInMs] [-modules \"module1[,module2...]\"]"

if [ $# -lt 2 ]; then
    echo $usage
    exit 3
fi

userHost=$1

accessor=$2

timeout=15000

modules=""

shift;shift
while [ $# -gt 0 ]
do
    key=$1
    case $key in
        -timeout|--timeout)
            if [ $# -lt 2 ]; then
                echo "$0: Usage $key must be followed by a timeout in ms."
                echo $usage
                exit 4
            fi
            timeout=$2
            shift
            ;;
        -modules|--modules)
            if [ $# -lt 2 ]; then
                echo "$0: Usage $key must be followed by one or more modules to be installed using npm"
                echo $usage
                exit 4
            fi
            modules=$2
            shift
            ;;
        *) "echo $0: argument $key is not understood?"
           exit 4;
            ;;
    esac
    shift
done

if [ $timeout = "15000" ]; then
    echo "$0: Note that the timeout defaults to $timeout"
fi

# Convert the comma separated list of modules to be installed to a space separated list.
modules=`echo $modules | sed 's/,/ /g'`

if [ ! -f "$accessor" ]; then
    echo "$0: $accessor could not be found?"
    exit 4
fi

runDirectory=/tmp/accessorInvokeSSH.$$

echo "### accessorInvokeSSH: Creating $runDirectory/node_modules on $userHost"
ssh $userHost mkdir -p $runDirectory/node_modules

# This assumes that npm is installed.
echo "### accessorInvokeSSH: Running npm install @terraswarm/accessors $modules"
echo "### accessorInvokeSSH:   Ignore messages like: 'npm WARN enoent ENOENT: no such file or directory, open $runDirectory/package.json'"
ssh $userHost "cd $runDirectory; npm install @terraswarm/accessors $modules"

echo "### accessorInvokeSSH: Creating $runDirectory/invoke.js"
echo "require('@terraswarm/accessors');invoke(process.argv);" | ssh $userHost "cat > $runDirectory/invoke.js"

remoteName="`basename $accessor`"

echo "### accessorInvokeSSH: Copying the accessor to $runDirectory"
scp $accessor $userHost:$runDirectory/$remoteName

# This assumes that node is installed.
echo "### accessorInvokeSSH: Invoking the accessor with $userHost node $runDirectory/invoke.js -timeout $timeout $runDirectory/$remoteName" 
ssh $userHost node $runDirectory/invoke.js -timeout $timeout $runDirectory/$remoteName 

#ssh $userHost rm -rf $runDirectory
