#!/bin/sh
# $Id$
# A script that deploys a composite accessor to a remote machine
#

if [ $# -ne 2 -a $# -ne 3 ]; then
    echo "$0: Usage: $0 remoteuser@remotehost compositeAccessor.js [timeout in ms]"
    exit 3
fi

userHost=$1

accessor=$2

timeout=5000
if [ $# -eq 3 ]; then
    timeout=$3
fi

if [ ! -f "$accessor" ]; then
    echo "$0: $accessor could not be found?"
    exit 4
fi

runDirectory=/tmp/accessorInvokeSSH.$$

ssh $userHost mkdir -p $runDirectory/node_modules

# This assumes that npm is installed.
ssh $userHost "cd $runDirectory; npm install @terraswarm/accessors"

echo "require('@terraswarm/accessors');invoke(process.argv);" | ssh $userHost "cat > $runDirectory/invoke.js"

remoteName="`basename $accessor .js``md5 $accessor | awk '{print $NF}'`.js"

scp $accessor $userHost:$runDirectory/$remoteName

# This assumes that node is installed.
ssh $userHost node $runDirectory/invoke.js -timeout $timeout $runDirectory/$remoteName 

#ssh $userHost rm -rf $runDirectory
