
interpreter.o: ${VMSRC}/interpreter.c ${EXTRADEP}
	${CC} ${CFLAGS} -c ${VMSRC}/interpreter.c

threads.o: ${VMSRC}/threads.c ${EXTRADEP}
	${CC} ${CFLAGS} -c ${VMSRC}/threads.c

exceptions.o: ${VMSRC}/exceptions.c ${EXTRADEP}
	${CC} ${CFLAGS} -c ${VMSRC}/exceptions.c

memory.o: ${VMSRC}/memory.c ${EXTRADEP}
	${CC} ${CFLAGS} -c ${VMSRC}/memory.c

language.o: ${VMSRC}/language.c ${EXTRADEP}
	${CC} ${CFLAGS} -c ${VMSRC}/language.c






