#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <jmi.h>
#include <jmi_block_residual.h>
#include "jmi_log.h"
#include "ModelicaUtilities.h"
#include "ModelicaStandardTables.h"

extern void dgemm_(char* TRANSA, char* TRANSB, int* M, int* N, int* K, double* ALPHA, double* A, int* LDA, double* B, int* LDB, double* BETA, double* C, int* LDC);

int model_ode_derivatives(jmi_t* jmi);
int model_ode_initialize(jmi_t* jmi);
int model_dae_R(jmi_t* jmi, jmi_real_t** res);
int model_init_R0(jmi_t* jmi, jmi_real_t** res);
void model_add_blocks(jmi_t** jmi);
void model_init_add_blocks(jmi_t** jmi);
int model_init_eval_parameters(jmi_t* jmi);
int jmi_set_start_values(jmi_t* jmi);
int model_ode_guards(jmi_t* jmi);
int model_ode_guards_init(jmi_t* jmi);


#define _clutch1_unitAngularAcceleration_39 ((*(jmi->z))[jmi->offs_real_ci+0])
#define _clutch1_unitTorque_40 ((*(jmi->z))[jmi->offs_real_ci+1])
#define _sin1_pi_48 ((*(jmi->z))[jmi->offs_real_ci+2])
#define _clutch2_unitAngularAcceleration_85 ((*(jmi->z))[jmi->offs_real_ci+3])
#define _clutch2_unitTorque_86 ((*(jmi->z))[jmi->offs_real_ci+4])
#define _clutch3_unitAngularAcceleration_122 ((*(jmi->z))[jmi->offs_real_ci+5])
#define _clutch3_unitTorque_123 ((*(jmi->z))[jmi->offs_real_ci+6])
#define _J4_flange_b_tau_126 ((*(jmi->z))[jmi->offs_real_ci+7])
#define _sin2_pi_137 ((*(jmi->z))[jmi->offs_real_ci+8])
#define _freqHz_0 ((*(jmi->z))[jmi->offs_real_pi+0])
#define _T2_1 ((*(jmi->z))[jmi->offs_real_pi+1])
#define _T3_2 ((*(jmi->z))[jmi->offs_real_pi+2])
#define _J1_J_3 ((*(jmi->z))[jmi->offs_real_pi+3])
#define _clutch1_mue_pos_1_1_11 ((*(jmi->z))[jmi->offs_real_pi+4])
#define _clutch1_mue_pos_1_2_12 ((*(jmi->z))[jmi->offs_real_pi+5])
#define _clutch1_peak_13 ((*(jmi->z))[jmi->offs_real_pi+6])
#define _clutch1_cgeo_14 ((*(jmi->z))[jmi->offs_real_pi+7])
#define _clutch1_fn_max_15 ((*(jmi->z))[jmi->offs_real_pi+8])
#define _clutch1_phi_nominal_23 ((*(jmi->z))[jmi->offs_real_pi+9])
#define _clutch1_w_small_25 ((*(jmi->z))[jmi->offs_real_pi+10])
#define _sin1_amplitude_43 ((*(jmi->z))[jmi->offs_real_pi+11])
#define _sin1_freqHz_44 ((*(jmi->z))[jmi->offs_real_pi+12])
#define _sin1_phase_45 ((*(jmi->z))[jmi->offs_real_pi+13])
#define _sin1_offset_46 ((*(jmi->z))[jmi->offs_real_pi+14])
#define _sin1_startTime_47 ((*(jmi->z))[jmi->offs_real_pi+15])
#define _step1_height_49 ((*(jmi->z))[jmi->offs_real_pi+16])
#define _step1_offset_50 ((*(jmi->z))[jmi->offs_real_pi+17])
#define _J2_J_52 ((*(jmi->z))[jmi->offs_real_pi+18])
#define _clutch2_mue_pos_1_1_57 ((*(jmi->z))[jmi->offs_real_pi+19])
#define _clutch2_mue_pos_1_2_58 ((*(jmi->z))[jmi->offs_real_pi+20])
#define _clutch2_peak_59 ((*(jmi->z))[jmi->offs_real_pi+21])
#define _clutch2_cgeo_60 ((*(jmi->z))[jmi->offs_real_pi+22])
#define _clutch2_fn_max_61 ((*(jmi->z))[jmi->offs_real_pi+23])
#define _clutch2_phi_nominal_69 ((*(jmi->z))[jmi->offs_real_pi+24])
#define _clutch2_w_small_71 ((*(jmi->z))[jmi->offs_real_pi+25])
#define _J3_J_89 ((*(jmi->z))[jmi->offs_real_pi+26])
#define _clutch3_mue_pos_1_1_94 ((*(jmi->z))[jmi->offs_real_pi+27])
#define _clutch3_mue_pos_1_2_95 ((*(jmi->z))[jmi->offs_real_pi+28])
#define _clutch3_peak_96 ((*(jmi->z))[jmi->offs_real_pi+29])
#define _clutch3_cgeo_97 ((*(jmi->z))[jmi->offs_real_pi+30])
#define _clutch3_fn_max_98 ((*(jmi->z))[jmi->offs_real_pi+31])
#define _clutch3_phi_nominal_106 ((*(jmi->z))[jmi->offs_real_pi+32])
#define _clutch3_w_small_108 ((*(jmi->z))[jmi->offs_real_pi+33])
#define _J4_J_127 ((*(jmi->z))[jmi->offs_real_pi+34])
#define _sin2_amplitude_132 ((*(jmi->z))[jmi->offs_real_pi+35])
#define _sin2_phase_134 ((*(jmi->z))[jmi->offs_real_pi+36])
#define _sin2_offset_135 ((*(jmi->z))[jmi->offs_real_pi+37])
#define _sin2_startTime_136 ((*(jmi->z))[jmi->offs_real_pi+38])
#define _step2_height_138 ((*(jmi->z))[jmi->offs_real_pi+39])
#define _step2_offset_139 ((*(jmi->z))[jmi->offs_real_pi+40])
#define _fixed_phi0_141 ((*(jmi->z))[jmi->offs_real_pi+41])
#define __block_jacobian_check_tol_181 ((*(jmi->z))[jmi->offs_real_pi+42])
#define __cs_rel_tol_183 ((*(jmi->z))[jmi->offs_real_pi+43])
#define __cs_step_size_185 ((*(jmi->z))[jmi->offs_real_pi+44])
#define __events_default_tol_187 ((*(jmi->z))[jmi->offs_real_pi+45])
#define __events_tol_factor_188 ((*(jmi->z))[jmi->offs_real_pi+46])
#define __nle_solver_default_tol_192 ((*(jmi->z))[jmi->offs_real_pi+47])
#define __nle_solver_max_residual_scaling_factor_194 ((*(jmi->z))[jmi->offs_real_pi+48])
#define __nle_solver_min_residual_scaling_factor_195 ((*(jmi->z))[jmi->offs_real_pi+49])
#define __nle_solver_min_tol_196 ((*(jmi->z))[jmi->offs_real_pi+50])
#define __nle_solver_regularization_tolerance_197 ((*(jmi->z))[jmi->offs_real_pi+51])
#define __nle_solver_step_limit_factor_198 ((*(jmi->z))[jmi->offs_real_pi+52])
#define __nle_solver_tol_factor_199 ((*(jmi->z))[jmi->offs_real_pi+53])
#define _step1_startTime_10 ((*(jmi->z))[jmi->offs_real_pd+0])
#define _sin2_freqHz_16 ((*(jmi->z))[jmi->offs_real_pd+1])
#define _step2_startTime_51 ((*(jmi->z))[jmi->offs_real_pd+2])
#define _clutch1_mue0_62 ((*(jmi->z))[jmi->offs_real_pd+3])
#define _clutch2_mue0_99 ((*(jmi->z))[jmi->offs_real_pd+4])
#define _clutch3_mue0_133 ((*(jmi->z))[jmi->offs_real_pd+5])
#define _torque_phi_support_140 ((*(jmi->z))[jmi->offs_real_pd+6])
#define _fixed_flange_phi_157 ((*(jmi->z))[jmi->offs_real_pd+7])
#define _torque_support_phi_158 ((*(jmi->z))[jmi->offs_real_pd+8])
#define _clutch1_Unknown_33 ((*(jmi->z))[jmi->offs_integer_ci+0])
#define _clutch1_Free_34 ((*(jmi->z))[jmi->offs_integer_ci+1])
#define _clutch1_Forward_35 ((*(jmi->z))[jmi->offs_integer_ci+2])
#define _clutch1_Stuck_36 ((*(jmi->z))[jmi->offs_integer_ci+3])
#define _clutch1_Backward_37 ((*(jmi->z))[jmi->offs_integer_ci+4])
#define _clutch2_Unknown_79 ((*(jmi->z))[jmi->offs_integer_ci+5])
#define _clutch2_Free_80 ((*(jmi->z))[jmi->offs_integer_ci+6])
#define _clutch2_Forward_81 ((*(jmi->z))[jmi->offs_integer_ci+7])
#define _clutch2_Stuck_82 ((*(jmi->z))[jmi->offs_integer_ci+8])
#define _clutch2_Backward_83 ((*(jmi->z))[jmi->offs_integer_ci+9])
#define _clutch3_Unknown_116 ((*(jmi->z))[jmi->offs_integer_ci+10])
#define _clutch3_Free_117 ((*(jmi->z))[jmi->offs_integer_ci+11])
#define _clutch3_Forward_118 ((*(jmi->z))[jmi->offs_integer_ci+12])
#define _clutch3_Stuck_119 ((*(jmi->z))[jmi->offs_integer_ci+13])
#define _clutch3_Backward_120 ((*(jmi->z))[jmi->offs_integer_ci+14])
#define __block_solver_experimental_mode_182 ((*(jmi->z))[jmi->offs_integer_pi+0])
#define __cs_solver_184 ((*(jmi->z))[jmi->offs_integer_pi+1])
#define __iteration_variable_scaling_189 ((*(jmi->z))[jmi->offs_integer_pi+2])
#define __log_level_190 ((*(jmi->z))[jmi->offs_integer_pi+3])
#define __nle_solver_max_iter_193 ((*(jmi->z))[jmi->offs_integer_pi+4])
#define __residual_equation_scaling_202 ((*(jmi->z))[jmi->offs_integer_pi+5])
#define _J1_stateSelect_4 ((*(jmi->z))[jmi->offs_integer_pi+6])
#define _clutch1_stateSelect_24 ((*(jmi->z))[jmi->offs_integer_pi+7])
#define _J2_stateSelect_53 ((*(jmi->z))[jmi->offs_integer_pi+8])
#define _clutch2_stateSelect_70 ((*(jmi->z))[jmi->offs_integer_pi+9])
#define _J3_stateSelect_90 ((*(jmi->z))[jmi->offs_integer_pi+10])
#define _clutch3_stateSelect_107 ((*(jmi->z))[jmi->offs_integer_pi+11])
#define _J4_stateSelect_128 ((*(jmi->z))[jmi->offs_integer_pi+12])
#define __block_jacobian_check_180 ((*(jmi->z))[jmi->offs_boolean_pi+0])
#define __enforce_bounds_186 ((*(jmi->z))[jmi->offs_boolean_pi+1])
#define __nle_solver_check_jac_cond_191 ((*(jmi->z))[jmi->offs_boolean_pi+2])
#define __rescale_after_singular_jac_200 ((*(jmi->z))[jmi->offs_boolean_pi+3])
#define __rescale_each_step_201 ((*(jmi->z))[jmi->offs_boolean_pi+4])
#define __runtime_log_to_file_203 ((*(jmi->z))[jmi->offs_boolean_pi+5])
#define __use_Brent_in_1d_204 ((*(jmi->z))[jmi->offs_boolean_pi+6])
#define __use_jacobian_equilibration_205 ((*(jmi->z))[jmi->offs_boolean_pi+7])
#define _torque_useSupport_9 ((*(jmi->z))[jmi->offs_boolean_pi+8])
#define _clutch1_useHeatPort_41 ((*(jmi->z))[jmi->offs_boolean_pi+9])
#define _clutch2_useHeatPort_87 ((*(jmi->z))[jmi->offs_boolean_pi+10])
#define _clutch3_useHeatPort_124 ((*(jmi->z))[jmi->offs_boolean_pi+11])
#define _der_clutch1_phi_rel_172 ((*(jmi->z))[jmi->offs_real_dx+0])
#define _der_clutch1_w_rel_173 ((*(jmi->z))[jmi->offs_real_dx+1])
#define _der_clutch2_phi_rel_174 ((*(jmi->z))[jmi->offs_real_dx+2])
#define _der_clutch2_w_rel_175 ((*(jmi->z))[jmi->offs_real_dx+3])
#define _der_clutch3_phi_rel_176 ((*(jmi->z))[jmi->offs_real_dx+4])
#define _der_clutch3_w_rel_177 ((*(jmi->z))[jmi->offs_real_dx+5])
#define _der_J4_phi_178 ((*(jmi->z))[jmi->offs_real_dx+6])
#define _der_J4_w_179 ((*(jmi->z))[jmi->offs_real_dx+7])
#define _clutch1_phi_rel_19 ((*(jmi->z))[jmi->offs_real_x+0])
#define _clutch1_w_rel_20 ((*(jmi->z))[jmi->offs_real_x+1])
#define _clutch2_phi_rel_65 ((*(jmi->z))[jmi->offs_real_x+2])
#define _clutch2_w_rel_66 ((*(jmi->z))[jmi->offs_real_x+3])
#define _clutch3_phi_rel_102 ((*(jmi->z))[jmi->offs_real_x+4])
#define _clutch3_w_rel_103 ((*(jmi->z))[jmi->offs_real_x+5])
#define _J4_phi_129 ((*(jmi->z))[jmi->offs_real_x+6])
#define _J4_w_130 ((*(jmi->z))[jmi->offs_real_x+7])
#define _J1_phi_5 ((*(jmi->z))[jmi->offs_real_w+0])
#define _J1_w_6 ((*(jmi->z))[jmi->offs_real_w+1])
#define _J1_a_7 ((*(jmi->z))[jmi->offs_real_w+2])
#define _torque_tau_8 ((*(jmi->z))[jmi->offs_real_w+3])
#define _clutch1_fn_17 ((*(jmi->z))[jmi->offs_real_w+4])
#define _clutch1_f_normalized_18 ((*(jmi->z))[jmi->offs_real_w+5])
#define _clutch1_a_rel_21 ((*(jmi->z))[jmi->offs_real_w+6])
#define _clutch1_tau_22 ((*(jmi->z))[jmi->offs_real_w+7])
#define _clutch1_tau0_26 ((*(jmi->z))[jmi->offs_real_w+8])
#define _clutch1_tau0_max_27 ((*(jmi->z))[jmi->offs_real_w+9])
#define _clutch1_sa_29 ((*(jmi->z))[jmi->offs_real_w+10])
#define _clutch1_lossPower_42 ((*(jmi->z))[jmi->offs_real_w+11])
#define _J2_phi_54 ((*(jmi->z))[jmi->offs_real_w+12])
#define _J2_w_55 ((*(jmi->z))[jmi->offs_real_w+13])
#define _J2_a_56 ((*(jmi->z))[jmi->offs_real_w+14])
#define _clutch2_fn_63 ((*(jmi->z))[jmi->offs_real_w+15])
#define _clutch2_f_normalized_64 ((*(jmi->z))[jmi->offs_real_w+16])
#define _clutch2_a_rel_67 ((*(jmi->z))[jmi->offs_real_w+17])
#define _clutch2_tau_68 ((*(jmi->z))[jmi->offs_real_w+18])
#define _clutch2_tau0_72 ((*(jmi->z))[jmi->offs_real_w+19])
#define _clutch2_tau0_max_73 ((*(jmi->z))[jmi->offs_real_w+20])
#define _clutch2_sa_75 ((*(jmi->z))[jmi->offs_real_w+21])
#define _clutch2_lossPower_88 ((*(jmi->z))[jmi->offs_real_w+22])
#define _J3_phi_91 ((*(jmi->z))[jmi->offs_real_w+23])
#define _J3_w_92 ((*(jmi->z))[jmi->offs_real_w+24])
#define _J3_a_93 ((*(jmi->z))[jmi->offs_real_w+25])
#define _clutch3_fn_100 ((*(jmi->z))[jmi->offs_real_w+26])
#define _clutch3_f_normalized_101 ((*(jmi->z))[jmi->offs_real_w+27])
#define _clutch3_a_rel_104 ((*(jmi->z))[jmi->offs_real_w+28])
#define _clutch3_tau_105 ((*(jmi->z))[jmi->offs_real_w+29])
#define _clutch3_tau0_109 ((*(jmi->z))[jmi->offs_real_w+30])
#define _clutch3_tau0_max_110 ((*(jmi->z))[jmi->offs_real_w+31])
#define _clutch3_sa_112 ((*(jmi->z))[jmi->offs_real_w+32])
#define _clutch3_lossPower_125 ((*(jmi->z))[jmi->offs_real_w+33])
#define _J4_a_131 ((*(jmi->z))[jmi->offs_real_w+34])
#define _der_J1_phi_159 ((*(jmi->z))[jmi->offs_real_w+35])
#define _der_J1_w_160 ((*(jmi->z))[jmi->offs_real_w+36])
#define _der_J2_phi_161 ((*(jmi->z))[jmi->offs_real_w+37])
#define _der_J2_w_162 ((*(jmi->z))[jmi->offs_real_w+38])
#define _der_J3_phi_163 ((*(jmi->z))[jmi->offs_real_w+39])
#define _der_J3_w_164 ((*(jmi->z))[jmi->offs_real_w+40])
#define _der_2_J1_phi_165 ((*(jmi->z))[jmi->offs_real_w+41])
#define _der_2_clutch1_phi_rel_166 ((*(jmi->z))[jmi->offs_real_w+42])
#define _der_2_J2_phi_167 ((*(jmi->z))[jmi->offs_real_w+43])
#define _der_2_clutch2_phi_rel_168 ((*(jmi->z))[jmi->offs_real_w+44])
#define _der_2_J3_phi_169 ((*(jmi->z))[jmi->offs_real_w+45])
#define _der_2_clutch3_phi_rel_170 ((*(jmi->z))[jmi->offs_real_w+46])
#define _der_2_J4_phi_171 ((*(jmi->z))[jmi->offs_real_w+47])
#define _time ((*(jmi->z))[jmi->offs_t])
#define _clutch1_mode_38 ((*(jmi->z))[jmi->offs_integer_d+0])
#define _clutch2_mode_84 ((*(jmi->z))[jmi->offs_integer_d+1])
#define _clutch3_mode_121 ((*(jmi->z))[jmi->offs_integer_d+2])
#define _clutch1_free_28 ((*(jmi->z))[jmi->offs_boolean_d+0])
#define _clutch1_startForward_30 ((*(jmi->z))[jmi->offs_boolean_d+1])
#define _clutch1_startBackward_31 ((*(jmi->z))[jmi->offs_boolean_d+2])
#define _clutch1_locked_32 ((*(jmi->z))[jmi->offs_boolean_d+3])
#define _clutch2_free_74 ((*(jmi->z))[jmi->offs_boolean_d+4])
#define _clutch2_startForward_76 ((*(jmi->z))[jmi->offs_boolean_d+5])
#define _clutch2_startBackward_77 ((*(jmi->z))[jmi->offs_boolean_d+6])
#define _clutch2_locked_78 ((*(jmi->z))[jmi->offs_boolean_d+7])
#define _clutch3_free_111 ((*(jmi->z))[jmi->offs_boolean_d+8])
#define _clutch3_startForward_113 ((*(jmi->z))[jmi->offs_boolean_d+9])
#define _clutch3_startBackward_114 ((*(jmi->z))[jmi->offs_boolean_d+10])
#define _clutch3_locked_115 ((*(jmi->z))[jmi->offs_boolean_d+11])
#define pre_der_clutch1_phi_rel_172 ((*(jmi->z))[jmi->offs_pre_real_dx+0])
#define pre_der_clutch1_w_rel_173 ((*(jmi->z))[jmi->offs_pre_real_dx+1])
#define pre_der_clutch2_phi_rel_174 ((*(jmi->z))[jmi->offs_pre_real_dx+2])
#define pre_der_clutch2_w_rel_175 ((*(jmi->z))[jmi->offs_pre_real_dx+3])
#define pre_der_clutch3_phi_rel_176 ((*(jmi->z))[jmi->offs_pre_real_dx+4])
#define pre_der_clutch3_w_rel_177 ((*(jmi->z))[jmi->offs_pre_real_dx+5])
#define pre_der_J4_phi_178 ((*(jmi->z))[jmi->offs_pre_real_dx+6])
#define pre_der_J4_w_179 ((*(jmi->z))[jmi->offs_pre_real_dx+7])
#define pre_clutch1_phi_rel_19 ((*(jmi->z))[jmi->offs_pre_real_x+0])
#define pre_clutch1_w_rel_20 ((*(jmi->z))[jmi->offs_pre_real_x+1])
#define pre_clutch2_phi_rel_65 ((*(jmi->z))[jmi->offs_pre_real_x+2])
#define pre_clutch2_w_rel_66 ((*(jmi->z))[jmi->offs_pre_real_x+3])
#define pre_clutch3_phi_rel_102 ((*(jmi->z))[jmi->offs_pre_real_x+4])
#define pre_clutch3_w_rel_103 ((*(jmi->z))[jmi->offs_pre_real_x+5])
#define pre_J4_phi_129 ((*(jmi->z))[jmi->offs_pre_real_x+6])
#define pre_J4_w_130 ((*(jmi->z))[jmi->offs_pre_real_x+7])
#define pre_J1_phi_5 ((*(jmi->z))[jmi->offs_pre_real_w+0])
#define pre_J1_w_6 ((*(jmi->z))[jmi->offs_pre_real_w+1])
#define pre_J1_a_7 ((*(jmi->z))[jmi->offs_pre_real_w+2])
#define pre_torque_tau_8 ((*(jmi->z))[jmi->offs_pre_real_w+3])
#define pre_clutch1_fn_17 ((*(jmi->z))[jmi->offs_pre_real_w+4])
#define pre_clutch1_f_normalized_18 ((*(jmi->z))[jmi->offs_pre_real_w+5])
#define pre_clutch1_a_rel_21 ((*(jmi->z))[jmi->offs_pre_real_w+6])
#define pre_clutch1_tau_22 ((*(jmi->z))[jmi->offs_pre_real_w+7])
#define pre_clutch1_tau0_26 ((*(jmi->z))[jmi->offs_pre_real_w+8])
#define pre_clutch1_tau0_max_27 ((*(jmi->z))[jmi->offs_pre_real_w+9])
#define pre_clutch1_sa_29 ((*(jmi->z))[jmi->offs_pre_real_w+10])
#define pre_clutch1_lossPower_42 ((*(jmi->z))[jmi->offs_pre_real_w+11])
#define pre_J2_phi_54 ((*(jmi->z))[jmi->offs_pre_real_w+12])
#define pre_J2_w_55 ((*(jmi->z))[jmi->offs_pre_real_w+13])
#define pre_J2_a_56 ((*(jmi->z))[jmi->offs_pre_real_w+14])
#define pre_clutch2_fn_63 ((*(jmi->z))[jmi->offs_pre_real_w+15])
#define pre_clutch2_f_normalized_64 ((*(jmi->z))[jmi->offs_pre_real_w+16])
#define pre_clutch2_a_rel_67 ((*(jmi->z))[jmi->offs_pre_real_w+17])
#define pre_clutch2_tau_68 ((*(jmi->z))[jmi->offs_pre_real_w+18])
#define pre_clutch2_tau0_72 ((*(jmi->z))[jmi->offs_pre_real_w+19])
#define pre_clutch2_tau0_max_73 ((*(jmi->z))[jmi->offs_pre_real_w+20])
#define pre_clutch2_sa_75 ((*(jmi->z))[jmi->offs_pre_real_w+21])
#define pre_clutch2_lossPower_88 ((*(jmi->z))[jmi->offs_pre_real_w+22])
#define pre_J3_phi_91 ((*(jmi->z))[jmi->offs_pre_real_w+23])
#define pre_J3_w_92 ((*(jmi->z))[jmi->offs_pre_real_w+24])
#define pre_J3_a_93 ((*(jmi->z))[jmi->offs_pre_real_w+25])
#define pre_clutch3_fn_100 ((*(jmi->z))[jmi->offs_pre_real_w+26])
#define pre_clutch3_f_normalized_101 ((*(jmi->z))[jmi->offs_pre_real_w+27])
#define pre_clutch3_a_rel_104 ((*(jmi->z))[jmi->offs_pre_real_w+28])
#define pre_clutch3_tau_105 ((*(jmi->z))[jmi->offs_pre_real_w+29])
#define pre_clutch3_tau0_109 ((*(jmi->z))[jmi->offs_pre_real_w+30])
#define pre_clutch3_tau0_max_110 ((*(jmi->z))[jmi->offs_pre_real_w+31])
#define pre_clutch3_sa_112 ((*(jmi->z))[jmi->offs_pre_real_w+32])
#define pre_clutch3_lossPower_125 ((*(jmi->z))[jmi->offs_pre_real_w+33])
#define pre_J4_a_131 ((*(jmi->z))[jmi->offs_pre_real_w+34])
#define pre_der_J1_phi_159 ((*(jmi->z))[jmi->offs_pre_real_w+35])
#define pre_der_J1_w_160 ((*(jmi->z))[jmi->offs_pre_real_w+36])
#define pre_der_J2_phi_161 ((*(jmi->z))[jmi->offs_pre_real_w+37])
#define pre_der_J2_w_162 ((*(jmi->z))[jmi->offs_pre_real_w+38])
#define pre_der_J3_phi_163 ((*(jmi->z))[jmi->offs_pre_real_w+39])
#define pre_der_J3_w_164 ((*(jmi->z))[jmi->offs_pre_real_w+40])
#define pre_der_2_J1_phi_165 ((*(jmi->z))[jmi->offs_pre_real_w+41])
#define pre_der_2_clutch1_phi_rel_166 ((*(jmi->z))[jmi->offs_pre_real_w+42])
#define pre_der_2_J2_phi_167 ((*(jmi->z))[jmi->offs_pre_real_w+43])
#define pre_der_2_clutch2_phi_rel_168 ((*(jmi->z))[jmi->offs_pre_real_w+44])
#define pre_der_2_J3_phi_169 ((*(jmi->z))[jmi->offs_pre_real_w+45])
#define pre_der_2_clutch3_phi_rel_170 ((*(jmi->z))[jmi->offs_pre_real_w+46])
#define pre_der_2_J4_phi_171 ((*(jmi->z))[jmi->offs_pre_real_w+47])
#define pre_clutch1_mode_38 ((*(jmi->z))[jmi->offs_pre_integer_d+0])
#define pre_clutch2_mode_84 ((*(jmi->z))[jmi->offs_pre_integer_d+1])
#define pre_clutch3_mode_121 ((*(jmi->z))[jmi->offs_pre_integer_d+2])
#define pre_clutch1_free_28 ((*(jmi->z))[jmi->offs_pre_boolean_d+0])
#define pre_clutch1_startForward_30 ((*(jmi->z))[jmi->offs_pre_boolean_d+1])
#define pre_clutch1_startBackward_31 ((*(jmi->z))[jmi->offs_pre_boolean_d+2])
#define pre_clutch1_locked_32 ((*(jmi->z))[jmi->offs_pre_boolean_d+3])
#define pre_clutch2_free_74 ((*(jmi->z))[jmi->offs_pre_boolean_d+4])
#define pre_clutch2_startForward_76 ((*(jmi->z))[jmi->offs_pre_boolean_d+5])
#define pre_clutch2_startBackward_77 ((*(jmi->z))[jmi->offs_pre_boolean_d+6])
#define pre_clutch2_locked_78 ((*(jmi->z))[jmi->offs_pre_boolean_d+7])
#define pre_clutch3_free_111 ((*(jmi->z))[jmi->offs_pre_boolean_d+8])
#define pre_clutch3_startForward_113 ((*(jmi->z))[jmi->offs_pre_boolean_d+9])
#define pre_clutch3_startBackward_114 ((*(jmi->z))[jmi->offs_pre_boolean_d+10])
#define pre_clutch3_locked_115 ((*(jmi->z))[jmi->offs_pre_boolean_d+11])


#define sf(i) (jmi->variable_scaling_factors[i])

#define _real_ci(i) ((*(jmi->z))[jmi->offs_real_ci+i])
#define _real_cd(i) ((*(jmi->z))[jmi->offs_real_cd+i])
#define _real_pi(i) ((*(jmi->z))[jmi->offs_real_pi+i])
#define _real_pd(i) ((*(jmi->z))[jmi->offs_real_pd+i])
#define _real_dx(i) ((*(jmi->z))[jmi->offs_real_dx+i])
#define _real_x(i) ((*(jmi->z))[jmi->offs_real_x+i])
#define _real_u(i) ((*(jmi->z))[jmi->offs_real_u+i])
#define _real_w(i) ((*(jmi->z))[jmi->offs_real_w+i])
#define _t ((*(jmi->z))[jmi->offs_t])

#define _real_d(i) ((*(jmi->z))[jmi->offs_real_d+i])
#define _integer_d(i) ((*(jmi->z))[jmi->offs_integer_d+i])
#define _integer_u(i) ((*(jmi->z))[jmi->offs_integer_u+i])
#define _boolean_d(i) ((*(jmi->z))[jmi->offs_boolean_d+i])
#define _boolean_u(i) ((*(jmi->z))[jmi->offs_boolean_u+i])

#define _pre_real_dx(i) ((*(jmi->z))[jmi->offs_pre_real_dx+i])
#define _pre_real_x(i) ((*(jmi->z))[jmi->offs_pre_real_x+i])
#define _pre_real_u(i) ((*(jmi->z))[jmi->offs_pre_real_u+i])
#define _pre_real_w(i) ((*(jmi->z))[jmi->offs_pre_real_w+i])

#define _pre_real_d(i) ((*(jmi->z))[jmi->offs_pre_real_d+i])
#define _pre_integer_d(i) ((*(jmi->z))[jmi->offs_pre_integer_d+i])
#define _pre_integer_u(i) ((*(jmi->z))[jmi->offs_pre_integer_u+i])
#define _pre_boolean_d(i) ((*(jmi->z))[jmi->offs_pre_boolean_d+i])
#define _pre_boolean_u(i) ((*(jmi->z))[jmi->offs_pre_boolean_u+i])

#define _sw(i) ((*(jmi->z))[jmi->offs_sw + i])
#define _sw_init(i) ((*(jmi->z))[jmi->offs_sw_init + i])
#define _pre_sw(i) ((*(jmi->z))[jmi->offs_pre_sw + i])
#define _pre_sw_init(i) ((*(jmi->z))[jmi->offs_pre_sw_init + i])
#define _guards(i) ((*(jmi->z))[jmi->offs_guards + i])
#define _guards_init(i) ((*(jmi->z))[jmi->offs_guards_init + i])
#define _pre_guards(i) ((*(jmi->z))[jmi->offs_pre_guards + i])
#define _pre_guards_init(i) ((*(jmi->z))[jmi->offs_pre_guards_init + i])

#define _atInitial (jmi->atInitial)



void func_Modelica_Math_Vectors_interpolate_def0(jmi_array_t* x_a, jmi_array_t* y_a, jmi_ad_var_t xi_v, jmi_ad_var_t iLast_v, jmi_ad_var_t* yi_o, jmi_ad_var_t* iNew_o);
jmi_ad_var_t func_Modelica_Math_Vectors_interpolate_exp0(jmi_array_t* x_a, jmi_array_t* y_a, jmi_ad_var_t xi_v, jmi_ad_var_t iLast_v);




