#!/bin/sh
rm -f opentime.plt ticks.plt runtime.plt realtime.plt memory.plt

for file in $*
do
    type=`echo $file | sed 's/pubSubAgg//' | sed 's/pubsub//' | sed 's/hierarchicalModel//' | sed 's/.out//' | awk -F _ '{print $1}'`

    awk -v type="$type" '
    $0 ~ /^Opened/ {
        #print "Open", type, $4
        open = $4
    }
    $2 == "ms." && $3 == "Memory:" { 
        if (count++ == 0) {
            #print "FirstRun", type, $1
            firstRun = $1
            mem = substr($4,1,length($4)-1)
            free = substr($6,1,length($6)-1)
            #print "FirstMemory", type, mem-free
            firstMemory = mem-free
        } else {
            run += $1
            memory += mem-free
        }    
    }
    END {
        printf("%20s & %5d ms. %5d ms. & %5d ms. & %5d K & %5.0f ms. & %5d K \\\\\n", type, open, firstRun, open+firstRun, firstMemory, run/(count-1), memory/(count-1));
        #print type, "&", firstRun, "ms. &", firstMemory , "K &",  run/(count-1), " ms. &", memory/(count-1), "K \\\\"
        #print "SubsequentRuns", type, run/(count-1)
        #print "SubsequentRuns", type, memory/(count-1)
    }
    ' $file  | sort -nr -k8
done

