/* Generated By:JavaScope: Do not edit this line. ConfigurableAttribute.java */
/* An attribute whose value can be set via the MoML configure tag.

 Copyright (c) 1998-2001 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS.

                                        PT_COPYRIGHT_VERSION_2
                                        COPYRIGHTENDKEY

@ProposedRating Green (eal@eecs.berkeley.edu)
@AcceptedRating Green (janneck@eecs.berkeley.edu)
*/

package ptolemy.kernel.util;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.IOException;
import java.io.Writer;
<<<<<<< ConfigurableAttribute.java
import java.net.URL; import COM.sun.suntest.javascope.database.js$;import COM.sun.suntest.javascope.database.CoverageUnit; 
=======
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.net.URL;
>>>>>>> 1.6

//////////////////////////////////////////////////////////////////////////
//// ConfigurableAttribute
/**
This class provides a simple way to get a long string into an attribute.
It implements Configurable, so its value can be set using a configure MoML
element.  For example,
<pre>
&lt;property name="x" class="ptolemy.moml.ConfigurableAttribute"&gt;
  &lt;configure source="url"&gt;xxx&lt;/configure&gt;
&lt;/property&gt;
</pre>
The value of this property, obtained via the value() method,
will be whatever text is contained by the referenced URL (which
is optional), followed by the text "xxx".

@author Steve Neuendorffer and Edward A. Lee
@version $Id$
*/

public class ConfigurableAttribute
<<<<<<< ConfigurableAttribute.java
    extends Attribute implements Configurable { static private int js$t0 = js$.setDatabase("/home/eecs/cxh/jsdatabase");static private String[] js$p={"ptolemy","kernel","util",};static private CoverageUnit js$c=js$.c(js$p,"ConfigurableAttribute","/export/maury/maury2/cxh/tmp/ptII/ptolemy/kernel/util/jsoriginal/ConfigurableAttribute.java",976122374900L,js$n());  static final int[] js$a = js$c.counters; 
=======
    extends Attribute implements Configurable, Settable {
>>>>>>> 1.6

    /** Construct a new attribute with no
     *  container and an empty string as its name. Add the attribute to the
     *  default workspace directory.
     *  Increment the version number of the workspace.
     */
    public ConfigurableAttribute() {
        super(); try{  js$.g(ConfigurableAttribute.js$a,1);  }finally{js$.flush(ConfigurableAttribute.js$c);} 
     js$.g(ConfigurableAttribute.js$a,0);/*$js$*/ }

    /** Construct a new attribute with
     *  no container and an empty string as a name. You can then change
     *  the name with setName(). If the workspace argument is null, then
     *  use the default workspace.
     *  Add the attribute to the workspace directory.
     *  Increment the version number of the workspace.
     *  @param workspace The workspace that will list the attribute.
     */
    public ConfigurableAttribute(Workspace workspace) {
	super(workspace); try{  js$.g(ConfigurableAttribute.js$a,3);  }finally{js$.flush(ConfigurableAttribute.js$c);} 
     js$.g(ConfigurableAttribute.js$a,2);/*$js$*/ }

    /** Construct a new attribute with the given container and name.
     *  @param container The container.
     *  @param name The name.
     *  @exception IllegalActionException If the attribute cannot be contained
     *   by the proposed container.
     *  @exception NameDuplicationException If the container already has an
     *   attribute with this name.
     */
    public ConfigurableAttribute(NamedObj container, String name)
            throws NameDuplicationException, IllegalActionException  {
	super(container, name); try{  js$.g(ConfigurableAttribute.js$a,5);  }finally{js$.flush(ConfigurableAttribute.js$c);} 
     js$.g(ConfigurableAttribute.js$a,4);/*$js$*/ }

    ///////////////////////////////////////////////////////////////////
    ////                         public methods                    ////

    /** Add a listener to be notified when the value of this attribute changes.
     *  If the listener is already on the list of listeners, then do nothing.
     *  @param listener The listener to add.
     */
    public void addValueListener(ValueListener listener) {
        if (_valueListeners == null) {
            _valueListeners = new LinkedList();
        }
        if (!_valueListeners.contains(listener)) {
            _valueListeners.add(listener);
        }
    }

    /** Configure the object with data from the specified input source
     *  (a URL) and/or textual data.  The input source, if any, is assumed
     *  to contain textual data as well.  Note that the URL is not read
     *  until the value() method is called.
     *  @param base The base relative to which references within the input
     *   are found, or null if this is not known, or there is none.
     *   This argument is ignored in this method.
     *  @param source The input source, which specifies a URL.
     *  @param text Configuration information given as text.
     *  @exception Exception Not thrown in this base class.
     */
    public void configure(URL base, String source, String text)
            throws Exception {try  { js$.g(ConfigurableAttribute.js$a,7); 
         js$.g(ConfigurableAttribute.js$a,6);/*$js$*/ _base = base;
        _source = source;
        _text = text;
<<<<<<< ConfigurableAttribute.java
    } finally{js$.flush(ConfigurableAttribute.js$c);}} 
=======
        // FIXME: Do we really want to call this right away?
        validate();
    }
>>>>>>> 1.6

    /** Return the base specified in the most recent call to the
     *  configure() method, or null if none.
     *  @return The base with respect to which the relative references
     *   in the source file should be interpreted.
<<<<<<< ConfigurableAttribute.java
     */
    public URL getBase() {try  { js$.g(ConfigurableAttribute.js$a,9); 
         js$.g(ConfigurableAttribute.js$a,8);/*$js$*/ return _base;
    } finally{js$.flush(ConfigurableAttribute.js$c);}} 

=======
     */
    public URL getBase() {
        return _base;
    }

    /** Return the the result of calling value().
     *  @return The value, or a description of the exception if one is thrown.
     *  @see #value()
     */
    public String getExpression() {
        try {
            return value();
        } catch (Exception ex) {
            return ex.toString();
        }
    }

>>>>>>> 1.6
    /** Return the source specified in the most recent call to the
     *  configure() method, or null if none.
     *  @return A URL specifying an external source for configure
     *   information.
     */
    public String getSource() {try  { js$.g(ConfigurableAttribute.js$a,11); 
         js$.g(ConfigurableAttribute.js$a,10);/*$js$*/ return _source;
    } finally{js$.flush(ConfigurableAttribute.js$c);}} 

    /** Return the text specified in the most recent call to the
     *  configure() method, or null if none.
     *  @return Text giving configure information.
     */
<<<<<<< ConfigurableAttribute.java
    public String getText() {try  { js$.g(ConfigurableAttribute.js$a,13); 
         js$.g(ConfigurableAttribute.js$a,12);/*$js$*/ return _text;
    } finally{js$.flush(ConfigurableAttribute.js$c);}} 

=======
    public String getText() {
        return _text;
    }

    /** Get the visibility of this attribute, as set by setVisibility().
     *  The visibility is set by default to NONE.
     *  @return The visibility of this attribute.
     */
    public Settable.Visibility getVisibility() {
        return _visibility;
    }

    /** Remove a listener from the list of listeners that is
     *  notified when the value of this attribute changes.  If no such listener
     *  exists, do nothing.
     *  @param listener The listener to remove.
     */
    public void removeValueListener(ValueListener listener) {
        if (_valueListeners != null) {
            _valueListeners.remove(listener);
        }
    }

    /** Set the value of the string attribute and notify the container
     *  of the value of this attribute by calling attributeChanged(),
     *  and notify any listeners that have
     *  been registered using addValueListener().  This is the same
     *  as calling configure with a null base and source, passing
     *  the argument as text.
     *  @param expression The text to configure the attribute with.
     *  @exception IllegalActionException If the change is not acceptable
     *   to the container.
     */
    public void setExpression(String expression) throws IllegalActionException {
        try {
            configure(null, null, expression);
        } catch (IllegalActionException ex) {
            throw ex;
        } catch (Exception ex) {
            throw new InternalErrorException("Unexpected exception: " + ex);
        }
    }

    /** Set the visibility of this attribute.  The argument should be one
     *  of the public static instances in Settable.
     *  @param visibility The visibility of this attribute.
     */
    public void setVisibility(Settable.Visibility visibility) {
        _visibility = visibility;
    }

    /** Validate any instances of Settable that this attribute may contain.
     *  Notify listeners that the value of this attribute has changed.
     *  @exception IllegalActionException If the change is not acceptable
     *   to the container.
     */
    public void validate() throws IllegalActionException {
        // Validate contained attributes, if any.
        Iterator attributes = attributeList(Settable.class).iterator();
        while(attributes.hasNext()) {
            Settable attribute = (Settable)attributes.next();
            attribute.validate();
        }
        // Notify the container that the attribute has changed.
        NamedObj container = (NamedObj)getContainer();
        if (container != null) {
            container.attributeChanged(this);
        }
        if (_valueListeners != null) {
            Iterator listeners = _valueListeners.iterator();
            while (listeners.hasNext()) {
                ValueListener listener = (ValueListener)listeners.next();
                listener.valueChanged(this);
            }
        }
    }

>>>>>>> 1.6
    /** Return the value given by the configure tag.  This is the text
     *  read from the specified URL (if any), followed by the text
     *  specified in the body of the configure element.  Note that the
     *  URL given in the configure() method, if any, is read each time
     *  this method is called.
     *  @return The value set in the configure tag.
     *  @exception IOException If the URL given in the configure method
     *   (if any) cannot be read.
     */
    public String value() throws IOException {try  { js$.g(ConfigurableAttribute.js$a,20); 
         js$.g(ConfigurableAttribute.js$a,14);/*$js$*/ StringBuffer value = new StringBuffer();
	// If a source is given, read its data.
        if ( ((( _source != null && !_source.trim().equals("") ) && ++ConfigurableAttribute.js$a[21] != 0) || ++ConfigurableAttribute.js$a[22] == 0) ) {
             js$.g(ConfigurableAttribute.js$a,15);/*$js$*/ URL textFile = new URL(_source);
            InputStream stream = textFile.openStream();
            BufferedReader reader = new BufferedReader(
                    new InputStreamReader(stream));
            String line = reader.readLine();
            while ( ((( line != null ) && ++ConfigurableAttribute.js$a[23] != 0) || ++ConfigurableAttribute.js$a[24] == 0) ) {
                 js$.g(ConfigurableAttribute.js$a,16);/*$js$*/ value.append(line);
                value.append("\n");
                line = reader.readLine();
            }
             js$.g(ConfigurableAttribute.js$a,17);/*$js$*/ reader.close();
            // NOTE: Do we need to close both?  Java docs don't say.
            stream.close();
        }
        if ( ((( _text != null ) && ++ConfigurableAttribute.js$a[25] != 0) || ++ConfigurableAttribute.js$a[26] == 0) ) {
             js$.g(ConfigurableAttribute.js$a,18);/*$js$*/ value.append(_text);
        }
	 js$.g(ConfigurableAttribute.js$a,19);/*$js$*/ return value.toString();
    } finally{js$.flush(ConfigurableAttribute.js$c);}} 

    ///////////////////////////////////////////////////////////////////
    ////                         protected methods                 ////

    /** Write a MoML description of the contents of this object.
     *  This method is called by exportMoML().  Each description
     *  is indented according to the
     *  specified depth and terminated with a newline character.
     *  @param output The output stream to write to.
     *  @param depth The depth in the hierarchy, to determine indenting.
     *  @exception IOException If an I/O error occurs.
     */
    protected void _exportMoMLContents(Writer output, int depth)
            throws IOException {try  { js$.g(ConfigurableAttribute.js$a,31); 
         js$.g(ConfigurableAttribute.js$a,27);/*$js$*/ super._exportMoMLContents(output, depth);
        String sourceSpec = "";
	if( ((( _source != null && !_source.trim().equals("") ) && ++ConfigurableAttribute.js$a[32] != 0) || ++ConfigurableAttribute.js$a[33] == 0) ) {
             js$.g(ConfigurableAttribute.js$a,28);/*$js$*/ sourceSpec = " source=\"" + _source + "\"";
            if ( ((( _text == null ) && ++ConfigurableAttribute.js$a[34] != 0) || ++ConfigurableAttribute.js$a[35] == 0) ) {
                 js$.g(ConfigurableAttribute.js$a,29);/*$js$*/ output.write(_getIndentPrefix(depth)
                        + "<configure" + sourceSpec + "/>\n");
            }
        }
        if ( ((( _text != null ) && ++ConfigurableAttribute.js$a[36] != 0) || ++ConfigurableAttribute.js$a[37] == 0) ) {
             js$.g(ConfigurableAttribute.js$a,30);/*$js$*/ output.write(_getIndentPrefix(depth)
                    + "<configure" + sourceSpec + ">"
                    + _text
                    + "</configure>\n");
        }
    } finally{js$.flush(ConfigurableAttribute.js$c);}} 

    ///////////////////////////////////////////////////////////////////
    ////                         private members                   ////

    // The base specified in the configure() method.
    private URL _base;

    // Listeners for changes in value.
    private List _valueListeners;

    // The URL from which configure data is read.
    private String _source;

    // The text in the body of the configure.
<<<<<<< ConfigurableAttribute.java
    private String _text; static private int js$n() {return 38;}  static private int js$t1=js$.flush(ConfigurableAttribute.js$c);private int js$t2=js$.flush(ConfigurableAttribute.js$c); 
}=======
    private String _text;

    // The visibility of this attribute, which defaults to NONE;
    private Settable.Visibility _visibility = Settable.NONE;
}
>>>>>>> 1.6
