/* Generated By:JavaScope: Do not edit this line. KernelException.java */
/* Base class for exceptions that report the names of Nameable objects.

 Copyright (c) 1997-2001 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS.

                                        PT_COPYRIGHT_VERSION_2
                                        COPYRIGHTENDKEY

@ProposedRating Green (eal@eecs.berkeley.edu)
@AcceptedRating Green (johnr@eecs.berkeley.edu)
*/

package ptolemy.kernel.util; import COM.sun.suntest.javascope.database.js$;import COM.sun.suntest.javascope.database.CoverageUnit; 

//////////////////////////////////////////////////////////////////////////
//// KernelException
/**
Base class for exceptions that report the names of Nameable objects.
This exception should not be thrown directly, since it provides very
little information about the cause of the exception.
This exception is not abstract so that we can easily test it.
If any or all of the arguments to the constructor are null, then the
detail message is adjusted accordingly.
Derived classes can provide multiple constructors that take 0, 1 or 2
Nameable references plus a detail String.

@author John S. Davis, II, Edward A. Lee
@version $Id$
*/
public class KernelException extends Exception { static private int js$t0 = js$.setDatabase("/home/eecs/cxh/jsdatabase");static private String[] js$p={"ptolemy","kernel","util",};static private CoverageUnit js$c=js$.c(js$p,"KernelException","/export/maury/maury2/cxh/tmp/ptII/ptolemy/kernel/util/jsoriginal/KernelException.java",976122374900L,js$n());  static final int[] js$a = js$c.counters; 

    /** Constructs an Exception with a no specific detail message */
    public KernelException() {
        // Note: this nullary exception is required.  If it is
        // not present, then the subclasses of this class will not
        // compile.
        this(null, null, null); try{  js$.g(KernelException.js$a,1);  }finally{js$.flush(KernelException.js$c);} 
     js$.g(KernelException.js$a,0);/*$js$*/ }

    /** Constructs an Exception with a detail message that includes the
     *  names of the first two arguments plus the third argument string.
     *  If one or more of the parameters are null, then the detail
     *  message is adjusted accordingly.
     *  @param obj1 The first object.
     *  @param obj2 The second object.
     *  @param detail The message.
     */
    public KernelException(Nameable obj1, Nameable obj2,
            String detail) { try{  js$.g(KernelException.js$a,9); 
         js$.g(KernelException.js$a,2);/*$js$*/ String obj1string = _getFullName(obj1);
        String obj2string = _getFullName(obj2);
        String prefix =null ;
        if ( ((( !obj1string.equals("") ) && ++KernelException.js$a[10] != 0) || ++KernelException.js$a[11] == 0) ) {
            if ( ((( !obj2string.equals("") ) && ++KernelException.js$a[12] != 0) || ++KernelException.js$a[13] == 0) ) {
                 js$.g(KernelException.js$a,3);/*$js$*/ prefix = new String(obj1string + " and " + obj2string);
            } else {
                 js$.g(KernelException.js$a,4);/*$js$*/ prefix = obj1string;
            }
        } else {
             js$.g(KernelException.js$a,5);/*$js$*/ prefix = obj2string;
        }
         js$.g(KernelException.js$a,6);/*$js$*/ _setMessage(prefix);
        if ( ((( detail != null ) && ++KernelException.js$a[14] != 0) || ++KernelException.js$a[15] == 0) ) {
            if ( ((( !detail.equals("") ) && ++KernelException.js$a[16] != 0) || ++KernelException.js$a[17] == 0) ) {
                if ( ((( !prefix.equals("") ) && ++KernelException.js$a[18] != 0) || ++KernelException.js$a[19] == 0) ) {
                     js$.g(KernelException.js$a,7);/*$js$*/ _setMessage(new String(prefix + ":\n" + detail));
                } else {
                     js$.g(KernelException.js$a,8);/*$js$*/ _setMessage(detail);
                }
            }
        } }finally{js$.flush(KernelException.js$c);} 
    }

    ///////////////////////////////////////////////////////////////////
    ////                         public methods                    ////

    /** Get the detail message.
     *  @return The error message.
     */
    public String getMessage() {try  { js$.g(KernelException.js$a,21); 
         js$.g(KernelException.js$a,20);/*$js$*/ return _message;
    } finally{js$.flush(KernelException.js$c);}} 

    ///////////////////////////////////////////////////////////////////
    ////                         protected methods                 ////

    /** Get the name of a Nameable object.
     *  If the argument is a null reference, return an empty string.
     *  @param obj An object with a name.
     *  @return The name of the argument.
     */
    protected String _getName(Nameable obj) {try  { js$.g(KernelException.js$a,27); 
         js$.g(KernelException.js$a,22);/*$js$*/ String name =null ;
        if ( ((( obj == null ) && ++KernelException.js$a[28] != 0) || ++KernelException.js$a[29] == 0) ) {
             js$.g(KernelException.js$a,23);/*$js$*/ return "";
        } else {
             js$.g(KernelException.js$a,24);/*$js$*/ name = obj.getName();
            if ( ((( name.equals("") ) && ++KernelException.js$a[30] != 0) || ++KernelException.js$a[31] == 0) ) {
                 js$.g(KernelException.js$a,25);/*$js$*/ name = new String("<Unnamed Object>");
            }
        }
         js$.g(KernelException.js$a,26);/*$js$*/ return name;
    } finally{js$.flush(KernelException.js$c);}} 

    /** Get the name of a Nameable object.  This method attempts to use
     *  getFullName(), if it is defined, and resorts to getName() if it is
     *  not.  If the argument is a null reference, return an empty string.
     *  @param obj An object with a full name.
     *  @return The full name of the argument.
     */
    protected String _getFullName(Nameable obj) {try  { js$.g(KernelException.js$a,37); 
         js$.g(KernelException.js$a,32);/*$js$*/ String name =null ;
        if ( ((( obj == null ) && ++KernelException.js$a[38] != 0) || ++KernelException.js$a[39] == 0) ) {
             js$.g(KernelException.js$a,33);/*$js$*/ return "";
        } else {
             js$.g(KernelException.js$a,34);/*$js$*/ try {
                name = obj.getFullName();
            } catch (InvalidStateException ex) { js$.g(KernelException.js$a,40); 
                 js$.g(KernelException.js$a,35);/*$js$*/ name = obj.getName();
            }
        }
         js$.g(KernelException.js$a,36);/*$js$*/ return name;
    } finally{js$.flush(KernelException.js$c);}} 

    /** Sets the error message to the specified string.
     *  @param msg The message.
     */
    protected void _setMessage(String msg) {try  { js$.g(KernelException.js$a,43); 
        if ( ((( msg == null ) && ++KernelException.js$a[44] != 0) || ++KernelException.js$a[45] == 0) ) {
             js$.g(KernelException.js$a,41);/*$js$*/ _message = "";
        } else {
             js$.g(KernelException.js$a,42);/*$js$*/ _message = msg;
        }
    } finally{js$.flush(KernelException.js$c);}} 

    ///////////////////////////////////////////////////////////////////
    ////                         private variables                 ////

    /** @serial The detail message. */
    private String _message ; static private int js$n() {return 46;}  static private int js$t1=js$.flush(KernelException.js$c);private int js$t2=js$.flush(KernelException.js$c); 
