/* Generated By:JavaScope: Do not edit this line. SingletonAttribute.java */
/* An attribute that replaces any previous instance with the same name.

 Copyright (c) 1998-2001 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS.

                                        PT_COPYRIGHT_VERSION_2
                                        COPYRIGHTENDKEY

@ProposedRating Green (eal@eecs.berkeley.edu)
@AcceptedRating Green (janneck@eecs.berkeley.edu)
*/

package ptolemy.kernel.util;

import java.io.Writer;
import java.io.IOException; import COM.sun.suntest.javascope.database.js$;import COM.sun.suntest.javascope.database.CoverageUnit; 

//////////////////////////////////////////////////////////////////////////
//// SingletonAttribute
/**
This class is an attribute that replaces any previously
existing SingletonAttribute in the container that has the same name.

@author Steve Neuendorffer and Edward A. Lee
@version $Id$
*/

public class SingletonAttribute extends Attribute { static private int js$t0 = js$.setDatabase("/home/eecs/cxh/jsdatabase");static private String[] js$p={"ptolemy","kernel","util",};static private CoverageUnit js$c=js$.c(js$p,"SingletonAttribute","/export/maury/maury2/cxh/tmp/ptII/ptolemy/kernel/util/jsoriginal/SingletonAttribute.java",976122374900L,js$n());  static final int[] js$a = js$c.counters; 

    /** Construct a new attribute with no
     *  container and an empty string as its name. Add the attribute to the
     *  workspace directory.
     *  Increment the version number of the workspace.
     */
    public SingletonAttribute() {
        super(); try{  js$.g(SingletonAttribute.js$a,1);  }finally{js$.flush(SingletonAttribute.js$c);} 
     js$.g(SingletonAttribute.js$a,0);/*$js$*/ }

    /** Construct a new attribute with
     *  no container and an empty string as a name. You can then change
     *  the name with setName(). If the workspace argument is null, then
     *  use the default workspace.
     *  Add the attribute to the workspace directory.
     *  Increment the version number of the workspace.
     *  @param workspace The workspace that will list the attribute.
     */
    public SingletonAttribute(Workspace workspace) {
	super(workspace); try{  js$.g(SingletonAttribute.js$a,3);  }finally{js$.flush(SingletonAttribute.js$c);} 
     js$.g(SingletonAttribute.js$a,2);/*$js$*/ }

    /** Construct an attribute with the given container and name.
     *  If an attribute already exists with the same name as the one
     *  specified here, that is an instance of class
     *  SingletonAttribute (or a derived class), then that
     *  attribute is removed before this one is inserted in the container.
     *  @param container The container.
     *  @param name The name of this attribute.
     *  @exception IllegalActionException If the attribute cannot be contained
     *   by the proposed container.
     *  @exception NameDuplicationException If the container already has an
     *   attribute with this name, and the class of that container is not
     *   SingletonAttribute.
     */
    public SingletonAttribute(NamedObj container, String name)
            throws NameDuplicationException, IllegalActionException  {
	super(container, name); try{  js$.g(SingletonAttribute.js$a,5);  }finally{js$.flush(SingletonAttribute.js$c);} 
     js$.g(SingletonAttribute.js$a,4);/*$js$*/ }

    ///////////////////////////////////////////////////////////////////
    ////                         public methods                    ////

    /** Remove any previous attribute in the container that has
     *  class SingletonAttribute and the same name as this
     *  attribute, and then call the base class method to set the container.
     *  If the container already contains an attribute with the same name
     *  that is not of class SingletonAttribute, then throw an
     *  exception and do not make any changes.  Similarly, if the container
     *  is not in the same workspace as this attribute, throw an exception.
     *  If this attribute is already contained by the NamedObj, do nothing.
     *  If the attribute already has a container, remove
     *  this attribute from its attribute list first.  Otherwise, remove
     *  it from the directory of the workspace, if it is there.
     *  If the argument is null, then remove this attribute from its
     *  container. It is not added to the workspace directory, so this
     *  could result in this object being garbage collected.
     *  <p>
     *  Note that since an Attribute is a NamedObj, it can itself have
     *  attributes.  However, recursive containment is not allowed, where
     *  an attribute is an attribute of itself, or indirectly of any attribute
     *  it contains.
     *  <p>
     *  This method is write-synchronized on the
     *  workspace and increments its version number.
     *  @param container The container to attach this attribute to.
     *  @exception IllegalActionException If this attribute is not of the
     *   expected class for the container, or it has no name,
     *   or the attribute and container are not in the same workspace, or
     *   the proposed container would result in recursive containment.
     *  @exception NameDuplicationException If the container already has
     *   an attribute with the name of this attribute that is of class
     *   SingletonAttribute.
     */
    public void setContainer(NamedObj container)
            throws IllegalActionException, NameDuplicationException {try  { js$.g(SingletonAttribute.js$a,14); 
         js$.g(SingletonAttribute.js$a,6);/*$js$*/ Attribute previous = null;
        if ( ((( container != null ) && ++SingletonAttribute.js$a[15] != 0) || ++SingletonAttribute.js$a[16] == 0) ) {
             js$.g(SingletonAttribute.js$a,7);/*$js$*/ previous = container.getAttribute(getName());
            if ( ((( previous instanceof SingletonAttribute ) && ++SingletonAttribute.js$a[17] != 0) || ++SingletonAttribute.js$a[18] == 0) ) {
                 js$.g(SingletonAttribute.js$a,8);/*$js$*/ previous.setContainer(null);
            }
        }
         js$.g(SingletonAttribute.js$a,9);/*$js$*/ try {
            super.setContainer(container);
        } catch (IllegalActionException ex) { js$.g(SingletonAttribute.js$a,19); 
            // Restore previous.
            if ( ((( previous instanceof SingletonAttribute ) && ++SingletonAttribute.js$a[20] != 0) || ++SingletonAttribute.js$a[21] == 0) ) {
                 js$.g(SingletonAttribute.js$a,10);/*$js$*/ previous.setContainer(container);
            }
             js$.g(SingletonAttribute.js$a,11);/*$js$*/ throw ex;
        } catch (NameDuplicationException ex) { js$.g(SingletonAttribute.js$a,22); 
            // Restore previous.
            if ( ((( previous instanceof SingletonAttribute ) && ++SingletonAttribute.js$a[23] != 0) || ++SingletonAttribute.js$a[24] == 0) ) {
                 js$.g(SingletonAttribute.js$a,12);/*$js$*/ previous.setContainer(container);
            }
             js$.g(SingletonAttribute.js$a,13);/*$js$*/ throw ex;
        }
    } finally{js$.flush(SingletonAttribute.js$c);}}  static private int js$n() {return 25;}  static private int js$t1=js$.flush(SingletonAttribute.js$c);private int js$t2=js$.flush(SingletonAttribute.js$c); 
