/* Generated By:JavaScope: Do not edit this line. StreamChangeListener.java */
/* A change listener that describes changes on the standard output.

 Copyright (c) 1998-2001 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS.

                                        PT_COPYRIGHT_VERSION_2
                                        COPYRIGHTENDKEY

@ProposedRating Green (eal@eecs.berkeley.edu)
@AcceptedRating Green (neuendor@eecs.berkeley.edu)
*/

package ptolemy.kernel.util;

import java.io.OutputStream;
import java.io.PrintStream; import COM.sun.suntest.javascope.database.js$;import COM.sun.suntest.javascope.database.CoverageUnit; 


//////////////////////////////////////////////////////////////////////////
//// StreamChangeListener
/**
A change listener that describes the changes on the standard output.
It simply prints the description of the change once it executes (or
throws an exception).

@author Edward A. Lee
@version $Id$
*/
public class StreamChangeListener implements ChangeListener { static private int js$t0 = js$.setDatabase("/home/eecs/cxh/jsdatabase");static private String[] js$p={"ptolemy","kernel","util",};static private CoverageUnit js$c=js$.c(js$p,"StreamChangeListener","/export/maury/maury2/cxh/tmp/ptII/ptolemy/kernel/util/jsoriginal/StreamChangeListener.java",976122374900L,js$n());  static final int[] js$a = js$c.counters; 

    /** Create a change listener that sends messages to the standard output.
     */
    public StreamChangeListener() { try{  js$.g(StreamChangeListener.js$a,1); 
         js$.g(StreamChangeListener.js$a,0);/*$js$*/ _output = System.out; }finally{js$.flush(StreamChangeListener.js$c);} 
    }

    /** Create a change listener that sends messages to the specified stream.
     *  @param out The stream to send messages to.
     */
    public StreamChangeListener(OutputStream out) { try{  js$.g(StreamChangeListener.js$a,3); 
         js$.g(StreamChangeListener.js$a,2);/*$js$*/ _output = new PrintStream(out); }finally{js$.flush(StreamChangeListener.js$c);} 
    }

    ///////////////////////////////////////////////////////////////////
    ////                         public methods                    ////

    /** Print the description of the change to the stream output.
     *  @param change The change that has been executed.
     */
    public void changeExecuted(ChangeRequest change) {try  { js$.g(StreamChangeListener.js$a,5); 
         js$.g(StreamChangeListener.js$a,4);/*$js$*/ _output.println("StreamChangeRequest.changeExecuted(): " +
                change.getDescription() +
                " succeeded");
    } finally{js$.flush(StreamChangeListener.js$c);}} 

    /** Print the description of the failure to the stream output.
     *  @param change The change that has been executed.
     *  @param exception The exception that occurred.
     */
    public void changeFailed(ChangeRequest change, Exception exception) {try  { js$.g(StreamChangeListener.js$a,7); 
         js$.g(StreamChangeListener.js$a,6);/*$js$*/ _output.println("StreamChangeRequest.changeFailed(): " +
                change.getDescription() +
                " failed: " + exception.toString());
    } finally{js$.flush(StreamChangeListener.js$c);}} 

    ///////////////////////////////////////////////////////////////////
    ////                         private variables                 ////

    private PrintStream _output; static private int js$n() {return 8;}  static private int js$t1=js$.flush(StreamChangeListener.js$c);private int js$t2=js$.flush(StreamChangeListener.js$c); 
