/* Generated By:JavaScope: Do not edit this line. ValueListener.java */
/* Listener for changes to object implementing Settable.

 Copyright (c) 1998-2001 The Regents of the University of California.
 All rights reserved.
 Permission is hereby granted, without written agreement and without
 license or royalty fees, to use, copy, modify, and distribute this
 software and its documentation for any purpose, provided that the above
 copyright notice and the following two paragraphs appear in all copies
 of this software.

 IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
 FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
 THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.

 THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
 PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
 CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
 ENHANCEMENTS, OR MODIFICATIONS.

                                        PT_COPYRIGHT_VERSION_2
                                        COPYRIGHTENDKEY
@ProposedRating Yellow (eal@eecs.berkeley.edu)
@AcceptedRating Red (reviewmoderator@eecs.berkeley.edu)

*/

package ptolemy.kernel.util; import COM.sun.suntest.javascope.database.js$;import COM.sun.suntest.javascope.database.CoverageUnit; 

//////////////////////////////////////////////////////////////////////////
//// ValueListener
/**
This is an interface for listeners that are notified when the value
of an object implementing Settable changes.

@author  Edward A. Lee
@version $Id$
@see ptolemy.data.expr.Variable
*/
public interface ValueListener { int js$t9761223840070 = js$.setDatabase("/home/eecs/cxh/jsdatabase");String[] js$p={"ptolemy","kernel","util",};CoverageUnit js$c=js$.c(js$p,"ValueListener","/export/maury/maury2/cxh/tmp/ptII/ptolemy/kernel/util/jsoriginal/ValueListener.java",976122374900L,js$ValueListener.js$n());  static final int[] js$a = js$c.counters; 

    ///////////////////////////////////////////////////////////////////
    ////                         public methods                    ////

    /** This is called to notify the listener that the value of the
     *  specified Settable has changed.
     *  @param settable The object that has changed value.
     */
    public void valueChanged(Settable settable); int js$t9761223840121=js$.flush(js$c); 
