#!/bin/sh
# Run the CT Corba Demo
# $PTII must be set
if [ -z "${PTII-}" ]; then
    echo "$0: \$PTII was not set, exiting."
    exit 3
fi

tnameserv -ORBInitialPort 1050 &
# Get the pid of the last process started up in the background
TPID=$!

CLASSPATH=$PTII
export CLASSPATH

java ptolemy.domains.ct.demo.Corba.ModelServer -ORBInitialPort 1050 &
MPID=$!

# Upon exit, kill these processes
trap "echo killing $TPID $MPID; kill $TPID $MPID" 1 2 3 9

appletviewer NonlinearClient.htm


