#!/bin/sh
# $Id$
# Script to harvest fix

if [ $# -lt 1 ]; then
    destinationSubdir=ptolemy/domains/sdf/cgc
    destinationDirectory=$PTII/$destinationSubdir/lib
    actors=`ls -1 $destinationDirectory/*.java`
else
    actors=$@
fi

for actor in $actors
do
    cat $actor |
       sed -e 's@//# line [0-9]*.*$@@' \
           -e 's@[ 	]*StringList \([a-z_0-9A-Z]*\) = \(".*"\);$@StringBuffer \1 = new StringBuffer(\2);@' \
	   -e 's@[ 	]*{[	 ]*StringList \([a-z_0-9A-Z]*\); \([a-z_0-9A-Z]*\) <<[	 ]*$@{ StringBuffer \1 = new StringBuffer(); \2.append(@' \
           -e 's@\([ 	]*addCode[^;]*;\) }[ 	]*$@); \1 } @' \
           -e 's@\([ 	]*addCode[^;]*;\)@\1 @' \
           -e 's@\([ 	]*[a-zA-Z0-9_]*\) << \(.*\);$@\1.append(\2);@' \
           -e 's@StringList \([a-z_0-9A-Z]*\);@StringBuffer \1 = new StringBuffer();@' \
	   -e 's@StringList \([a-z_0-9A-Z]*\) = \([^;]*\);$@StringBuffer \1 = new StringBuffer(\2);@' \
           -e 's@Error::abortRun[ ]*(\*this,@throw new IllegalActionException(this,@' \
           -e 's@" <<@" +@g' \
           -e 's@<< "@ + "@g' \
           -e 's@const char *\*@String@' \
           -e 's@int(\([a-z_0-9A-Z]*\))@((IntToken)(\1).getToken()).intValue()@g' \
           -e 's@double(\([a-z_0-9A-Z]*\))@((doubleToken)(\1).getToken()).doubleValue()@g' \
           -e 's@\([a-9_0-9A-Z]*\)[ ]*::[ ]*\([a-9_0-9A-Z]*\)@\1.\2@g' \
	   -e 's@this->@this.@g' \
	   -e 's@\(i>1."complex temp;":"/.Unit gain - no multiplication required./"\)@(\1)@' \
               > $actor.tmp

    # FIXME: fix the package
    dirname=`dirname $actor`
    dirdirname=`dirname $dirname`
    basedirname=`basename $dirdirname`
    if [ "x$basedirname" != "x." -a "$basedirname" != "cgc" ]; then
	cat $actor.tmp |
	    sed -e "s/package ptolemy.domains.sdf.cgc.lib;/package ptolemy.domains.sdf.cgc.${basedirname}.lib;/" > $actor.tmp2
	mv $actor.tmp2 $actor.tmp
    fi	
    diff $actor $actor.tmp 
    cp $actor.tmp $actor
done
