package ptolemy.actor.corba.RemoteManagerUtil;


/**
* ptolemy/actor/corba/RemoteManagerUtil/RemoteManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from RemoteManager.idl
* Thursday, January 16, 2003 3:50:31 PM PST
*/


/* A CORBA compatible interface that implements the execution
	 * methods of Ptolemy II.
	 */
public interface RemoteManager extends RemoteManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface RemoteManager
