#!/bin/sh

##### SETTINGS #####
SRC_DIR=${PTII}/ptolemy/domains/ptinyos/util/nc2moml
####################

if [ -z $TOSROOT ]; then
  echo "Error: \$TOSROOT must be defined"
  exit 0
fi
TOS_INPUT_DIR=$TOSROOT

if [ -z $PTII ]; then
  echo "Error: \$PTII must be defined"
fi

MOML_OUTPUT_DIR=$PTII/vendors/ptinyos/moml

DIR_LIST="tos/lib tos/system tos/platform tos/sensorboards"


echo "$SRC_DIR/nc2moml-main $TOS_INPUT_DIR \\\''\$CLASSPATH'\\\' $MOML_OUTPUT_DIR $DIR_LIST"

$SRC_DIR/nc2moml-main $TOS_INPUT_DIR \\\''\$CLASSPATH'\\\' $MOML_OUTPUT_DIR $DIR_LIST
