# $Id: makefile 67777 2013-10-26 01:51:06Z cxh $
# The name of the FMU to be built.
FMU_NAME = heaterFlowResistance

# The rules are in a separate file so that we can easily update them.
include fmu.mk
