#! /bin/sh
# $Id$
# Remove cruft from the current directory
/usr/bin/find . \( -name "#*" -o -name alljtests.tcl -o -name alljsimpletests.tcl -o -name codeDoc -o -name CVS -o -name .cvsignore -o -name "*~" -o -name core -o -name "*.out" -o -name "hs_err_pid*" \)  -exec rm -rf {} \;
