package ptolemy.domains.ct.demo.Corba.util;

/**
 * ptolemy/domains/ct/demo/Corba/util/CorbaUnknownPortException.java
 * Generated by the IDL-to-Java compiler (portable), version "3.0"
 * from CorbaActor.idl
 * Thursday, January 18, 2001 5:51:19 PM PST
 */
public final class CorbaUnknownPortException extends
        org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity {
    public String portName = null;

    public String message = null;

    public CorbaUnknownPortException() {
    } // ctor

    public CorbaUnknownPortException(String _portName, String _message) {
        portName = _portName;
        message = _message;
    } // ctor
} // class CorbaUnknownPortException
