package ptolemy.domains.ct.demo.Corba.util;

/**
 * ptolemy/domains/ct/demo/Corba/util/CorbaActor.java
 * Generated by the IDL-to-Java compiler (portable), version "3.0"
 * from CorbaActor.idl
 * Thursday, January 18, 2001 5:51:19 PM PST
 */

/* A CORBA compatible interface that implements the execution
 * methods of Ptolemy II.
 */
public interface CorbaActor extends CorbaActorOperations, org.omg.CORBA.Object,
        org.omg.CORBA.portable.IDLEntity {
} // interface CorbaActor
