#! /bin/sh
# $Id$
# Find all the SDF tests in the tree
cd $PTII

find . -name auto | awk '{print "ls " $1 "/*.xml"}' > /tmp/alltests.sh
sh /tmp/alltests.sh > /tmp/alltests
echo "All tests: `cat /tmp/alltests | wc -l`"

grep SDFDirector `cat /tmp/alltests` | awk -F : '{ print $1}' | sort | uniq > /tmp/sdftests.0
echo "All SDF tests: `cat /tmp/sdftests.0 | wc -l `"

cat /tmp/sdftests.0 | egrep -v "(/cg/|/codegen/|/jai/|/jmf/)" | sort > /tmp/sdftests.1
echo "All SDF tests except cg, codegen, jai jmf: `cat /tmp/sdftests.1 | wc -l`"

egrep "(DEDirector|FSMActor|ModalController|PNDirector)" `cat /tmp/sdftests.1` | sort | awk -F : '{print $1}' | sort | uniq > /tmp/sdftests.2
echo "SDF tests that have DE, FSM or PN: `cat /tmp/sdftests.2 | wc -l`"

comm -23 /tmp/sdftests.1 /tmp/sdftests.2 > /tmp/sdftests.3
echo "SDF tests that might work: `cat /tmp/sdftests.3 | wc -l`"

egrep -v "(CRoom.xml)" /tmp/sdftests.3 > /tmp/sdftests.4
echo "SDF tests that don't hang: `cat /tmp/sdftests.4 | wc -l`"


cat /tmp/sdftests.4 | sed 's@\./@$PTII/@' | awk '{print $1 " \\"}' > /tmp/sdftests.5

echo "See /tmp/sdftest.5 for contents suitable for AllSDF.tcl"

