#!/bin/sh
# $Id$
# Update fmu files from fmusdk

fmus=`find $PTII/org/ptolemy/fmi/fmu -name "*.fmu"`

arch=linux64
fmuSdkDirectory=$PTII/vendors/fmusdk/fmu

for fmu in $fmus
do
    base=`basename $fmu .fmu`
    echo $base
    directory=`dirname $fmu`
    csOrMe=`basename $directory`

    fmuDirectory=$directory/$base
    rm -rf $fmuDirectory
    mkdir $fmuDirectory

    # The fmu file in fmusdk
    fmuSdk=$fmuSdkDirectory/$csOrMe/$base.fmu
    (cd $fmuDirectory; unzip $fmuSdk)
    
    # Update the architecture
    (cd $fmuDirectory; zip $fmu binaries/$arch/*)
done
