#!/bin/sh
# $Id$
# Update fmu files from fmusdk

fmus=`find $PTII/org/ptolemy/fmi/fmu -name "*.fmu"`

arch=win64
x64=
if [ $arch = "win64" ]; then
    x64=/x64
fi
fmuSdkDirectory=$PTII/vendors/fmusdk/fmu

for fmu in $fmus
do
    base=`basename $fmu .fmu`
    echo $base
    directory=`dirname $fmu`
    csOrMe=`basename $directory`

    case $fmu in
	*20.fmu) fmi10or20=20;;
	*) fmi10or20=10;;
    esac
    
    fmuDirectory=$directory/$base
    rm -rf $fmuDirectory
    mkdir $fmuDirectory

    # The fmu file in the fmusdk.
    fmuSdk=$fmuSdkDirectory/fmu${fmi10or20}/$csOrMe${x64}/$base.fmu

    echo "updating $fmu with $fmuSdk"
    
    (cd $fmuDirectory; unzip $fmuSdk)
    
    # Update the architecture
    (cd $fmuDirectory; zip $fmu binaries/$arch/*)

    rm -rf $fmuDirectory
done
