#!/bin/sh
# $Id$
# Script that updates the demos

demos=`cd $PTII/ptolemy/configs/doc; make --no-print-directory listDemos |  egrep -v '(iRobotCreateVerification|Matlab|SystemLevelType)' `

# Create missing applets
#demos=`cd $PTII/ptolemy/configs/doc; make check_applets |  grep -v /SystemLevelType/ | sed 's/.htm$/.xml/'`

#demos=../../../ptolemy/domains/ddf/demo/IfThenElse/IfThenElseFSM.xml
#demos=../../../ptolemy/domains/continuous/demo/TwoMachineInfiniteBusControl/TwoMachineInfiniteBusControl.xml
#demos=../../../ptolemy/domains/continuous/demo/SinuBouncingBall/SinuBouncingBall.xml
demos=../../../ptolemy/domains/continuous/demo/NewtonsCradle/NewtonsCradleComplicated
#demos=../../../ptolemy/actor/gt/demo/BouncingBallX2/BouncingBallX2.xml 
#demos=../../../lbnl/demo/SystemCommand/SystemCommand.xml

for demo in $demos
do
    echo $demo
     model=`basename $demo .xml` 

     modelDirectory=`dirname $demo`
     modelPath=`cd $PTII/ptolemy/configs/doc/$modelDirectory; pwd`

     targetPath=`echo $modelPath | sed "s@$PTII/@@"`

     (cd $modelPath; tar -cf - *.jar *.jnlp *JNLP.htm $model) | ssh moog "cd ~www/ptweb/ptolemyII/ptII10.0/ptII10.0.devel/$targetPath; tar -xpf -"

done
