#!/bin/sh
# $Id$
# Script that updates the demos

demos=`cd $PTII/ptolemy/configs/doc; make --no-print-directory listDemos |  egrep -v '(iRobotCreateVerification|Matlab|SystemLevelType)' `

# Create missing applets
#demos=`cd $PTII/ptolemy/configs/doc; make check_applets |  grep -v /SystemLevelType/ | sed 's/.htm$/.xml/'`

#demos=../../../ptolemy/domains/ddf/demo/IfThenElse/IfThenElseFSM.xml
for demo in $demos
do
     model=`basename $demo .xml` 

     modelDirectory=`dirname $demo`
     modelPath=`cd $PTII/ptolemy/configs/doc/$modelDirectory; pwd`

     targetPath=`echo $modelPath | sed "s@$PTII/@@"`

     scp $modelPath/*.jar $modelPath/*.jnlp $modelPath/*JNLP.htm bennett:~ptII/ptweb/ptolemyII/ptII8.0/ptII8.0.1/$targetPath

done