#!/bin/sh
# $Id$
# Script that updates the demos

demos=`cd $PTII/ptolemy/configs/doc; make listDemos |  grep -v /SystemLevelType/`

# Create missing applets
#demos=`cd $PTII/ptolemy/configs/doc; make check_applets |  grep -v /SystemLevelType/ | sed 's/.htm$/.xml/'`

for demo in $demos
do
     model=`basename $demo .xml` 

     modelDirectory=`dirname $demo`
     modelPath=`cd $PTII/ptolemy/configs/doc/$modelDirectory; pwd`

     targetPath=`echo $modelPath | sed "s@$PTII/@@"`

     #echo "make MODEL=$model MODELPATH=$modelPath/$model.xml TARGETPATH=$targetPath jnlpUpdateDemo"
     echo $modelPath/$model.htm

     #rm $modelPath/$model.htm
     #svn update $modelPath/$model.htm
     htmlFile=$modelPath/$model.htm
#      if [ -f  $htmlFile ]; then
# 	 grep "PT JNLP APPLET CONVERTER" $htmlFile > /dev/null
# 	 status=$?
# 	 if [ $status -eq 0 ]; then
# 	     sed -e 's/width = ".*"/width = "100"/' \
# 	         -e's/height = ".*"/height = "100"/' < $htmlFile > /tmp/updateDemos.tmp
# 	     diff /tmp/updateDemos.tmp $htmlFile
# 	     #cp /tmp/updateDemos.tmp $htmlFile
# 	     echo "$htmlFile" >> /tmp/hfiles
# 	 fi
#      fi

     #if [ -f  $modelPath/$model.htm ]; then
# 	 rm $modelPath/$model.htm
# 	 svn update $modelPath/$model.htm
# 	 sed -e "s@ptinyViewer [^>]*>@ptinyViewer $targetPath/$model.xml\">@" \
# 	     -e "s@fullViewer [^>]*>@fullViewer $targetPath/$model.xml\">@" \
# 	     $modelPath/$model.htm > /tmp/$model.htm 

#     if [ -f  $modelPath/$model.htm -a -f $modelPath/${model}JNLP.htm ]; then
#          awk '{ if ($0 ~ /<!-- PT JNLP CONVERTER -->/) {
#                    exit;
#                 } 
#                 print $0
#           }' $modelPath/$model.htm > /tmp/$model.htm


# 	 awk '{if ($0 ~ /<!-- PT JNLP APPLET CONVERTER -->/) {
#                   sawJNLPAppletConverter = 1
#                }
#                if (sawJNLPAppletConverter == 1) {
#                   print $0
#                }
#                if ($0 ~ /<!-- \/PT JNLP APPLET CONVERTER -->/) {
#                   exit
#                }
#               }' $modelPath/${model}JNLP.htm >> /tmp/$model.htm

#          awk '{ if (sawJNLPConverter == 1) {
#                    print $0
#                 }
#                 if ($0 ~ /<!-- \/PT JNLP CONVERTER -->/) {
#                    sawJNLPConverter = 1;
#                 } 
#            }' $modelPath/$model.htm >> /tmp/$model.htm


#          awk -v jnlpFile=$model.jnlp '{ if ($0 ~ /<!-- HTML CONVERTER -->/) {
# 	        sawHTMLConverter = 1
# 	        print "<!-- PT JNLP CONVERTER -->";
#                 print "<a href=\"" jnlpFile "\">Run the demo using Web Start</a>";
# 	    } else if ($0 ~ /<!-- \/HTML CONVERTER -->/) {
# 	        sawHTMLConverter = 0 
# 	        print "<!-- /PT JNLP CONVERTER -->";
# 	    } else if (sawHTMLConverter == 0) {
# 	        print $0
#             }  
#           }' $modelPath/$model.htm > /tmp/$model.htm

#          diff /tmp/$model.htm $modelPath/$model.htm
#	  cp /tmp/$model.htm $modelPath/$model.htm
#	  ls -l /tmp/$model.htm $modelPath/$model.htm
#	  echo $modelPath/$model.htm
	  
     #fi
done