#! /bin/sh -x
# Test script for Java implementation of pxgraph
# @Author: Christopher Hylands
# @Version: $Id$

pxgraph=./pxgraph

# Create a small test file

tmpfile=/tmp/testpxgraph.$$
# Note that we don't have a DataSets starting the file, and
# that we use tabs, spaces and commas to separate the values
cat > $tmpfile <<EOF
0  0
1	1
2,2
3 -0.2
EOF

tmpfile2=/tmp/testpxgraph2.$$
# Note that we don't have a DataSets starting the file, and
# that we use tabs, spaces and commas to separate the values
cat > $tmpfile2 <<EOF
0 1
1 2
2 2.5
3 1
EOF

# Test out two file invocations
$pxgraph -test $tmpfile $tmpfile2
$pxgraph -test -0 "first data set" -1 "second data set" $tmpfile $tmpfile2
$pxgraph -test -0 "first data set" $tmpfile $tmpfile2
$pxgraph -test -1 "second data set" $tmpfile $tmpfile2
$pxgraph -test -2 "second data set" $tmpfile $tmpfile2
$pxgraph -test -0 "zero" -binary bin.plt

$pxgraph -test -bar -0 "first data set" -1 "second data set" $tmpfile $tmpfile2

# Test out Flags in order
$pxgraph -test $tmpfile
$pxgraph -test -bar $tmpfile
$pxgraph -test -bb $tmpfile
$pxgraph -test -binary bin.plt
$pxgraph -test -bar -binary bin.plt
$pxgraph -test -db $tmpfile
$pxgraph -help $tmpfile
$pxgraph -test -lnx $tmpfile
$pxgraph -test -lny $tmpfile
$pxgraph -test -m $tmpfile
$pxgraph -test -M $tmpfile
$pxgraph -test -nl $tmpfile
$pxgraph -test -p $tmpfile
$pxgraph -test -p -nl $tmpfile
$pxgraph -test -P $tmpfile
$pxgraph -test -P -nl -binary bin.plt
$pxgraph -test -P -nl $tmpfile
$pxgraph -test -rv $tmpfile
$pxgraph -test -tk $tmpfile
$pxgraph -test -v $tmpfile

# Test out Options in order
$pxgraph -test -bd Blue $tmpfile
$pxgraph -test -bg Green $tmpfile
$pxgraph -test -brb 1.0 -bar $tmpfile
$pxgraph -test -brw 0.8 -bar $tmpfile
$pxgraph -test -fg Pink $tmpfile
$pxgraph -test -gw 10 $tmpfile
$pxgraph -test -lf 9x15 $tmpfile
$pxgraph -test -lx 0.5,1.5 $tmpfile
$pxgraph -test -ly 0.5,1.5 $tmpfile
$pxgraph -test -lx 0.5,1.5 -ly 0.5,1.5 $tmpfile
$pxgraph -test -t "This is the Title" $tmpfile
$pxgraph -test -tf 9x15 $tmpfile
$pxgraph -test -x Years -y "$ Profit" $tmpfile
$pxgraph -test -zg Yellow $tmpfile
$pxgraph -test -zw 5 $tmpfile
rm -f $tmpfile $tmpfile2

# Test out stdin
$pxgraph -test < demo/data.plt

# Test out file args
$pxgraph -test ./demo/bargraph.plt
$pxgraph -test http://ptolemy.eecs.berkeley.edu/java/plot/demo/data.plt

# Sample run from Ptolemy
$pxgraph -test -t "Integer delays" -P -0 new -1 old =600x170+0+360 -binary bin.plt

