#!/bin/sh
# $Id$
# Update the website
# Usage: updatewebsite jnlpfile url

if [ $# -ne 2 ]; then
   echo "Usage: $0 jnlpfile remotedir"
   echo "For example:"
   echo "./updatewebsite AbsentLoop.jnlp /export/home/pt0/ptweb/ptolemyII/ptII8.0/jnlp-books"
   exit 2
fi

jnlpfile=$1
if [ -f $jnlpfile.fixed ] ; then
   jnlpfile=$jnlpfile.fixed
fi

remotedir=$2
basename=`basename $jnlpfile .jnlp`
jarfile=signed_$basename.jar

jars=`grep .jar $jnlpfile | awk -F \" '{print $(NF-1)}'`
(cd $PTII; tar -cf - $jars) | ssh bennett -l ptII "cd $remotedir; tar -xf -"

PWD=`pwd`
relativeDirectory=`echo $PWD | sed "s@$PTII/@@"`
ssh ptII@bennett "mkdir -p $remotedir/$relativeDirectory"
scp $jnlpfile ptII@bennett:$remotedir/$relativeDirectory/`basename $jnlpfile .fixed`
