#!/bin/sh
# $Id$
# Fix the OpenModelica FMU Makefile.
# See https://trac.openmodelica.org/OpenModelica/ticket/3615:RHEL 6.7: VanDerPol FMU fails to compile: undefined reference to clock_gettime
# See https://trac.openmodelica.org/OpenModelica/ticket/3616: RHEL 6.7: FMU fails to compile: stringAppend missing

omc=`which omc`

omcBin=`dirname $omc`

omcDir=`dirname $omcBin`

omcLibOmc="$omcDir/lib/omc"

# Attempt to deal with having /usr/local/bin/omc in the path
runtime=`find $omcLibOmc -name "libSimulationRuntimeC.*" | head -1`
if [ ! -f $runtime ]; then
    if [ ! -d $omcLibOmc ]; then
	omcLibOmc=/usr/local/openmodelica/lib/omc
        if [ ! -d $omcLibOmc ]; then
	    omcLibOmc=/usr/local/lib
        fi
    fi
fi

sed "s=^\(LDFLAGS.*\)$=\1 -lrt -L$omcLibOmc -lSimulationRuntimeC=" Makefile > Makefile.tmp

mv Makefile.tmp Makefile
