#!/bin/sh
# $Id$
# Start Xvfb, save the DOPCenter image, stop Xvfb

echo "Starting Xvfb"
Xvfb :1 -screen 0 1024x768x24 &
export DISPLAY=localhost:1.0

echo "Loading DOPCenter model, running it and exporting"
chmod 0400 $HOME/.spacecadet
$PTII/ptolemy/domains/space/demo/DOPCenter/updateDOPCenterImage
ls -l $PTII/ptolemy/domains/space/demo/DOPCenter/DOPCenter.png

echo "Killing Xvfb"
pkill Xvfb
pkill -9 Xvfb
