#!/bin/sh
# Update test/ directories with copies of
# JUnitTclTest that has the proper package

tmpmakefile=/tmp/updateJUnitTclTest$$.mk
cd $PTII

#testDirs=`adm/bin/ptIItxtfiles | grep testDefs.tcl | sed 's@/testDefs.tcl@@' | grep -v util/testsuite`

testDirs=./ptolemy/kernel/test

for testDir in $testDirs
do
    echo $testDir
    package=`echo $testDir | sed 's@/@.@g' | sed 's@\.\.@@g'`
    sed "s@/PACKAGE/@$package@" $PTII/util/testsuite/junit/JUnitTclTest.java.in > $testDir/JUnitTclTest.java
    awk '{
        if ($1 != "CLASSPATH") {
            if ($1 == "JSRCS") {
                jsrcLineNumber = NR
                print $0
            } else {
                if (jsrcLineNumber > 0 && NR == jsrcLineNumber + 1 && $0 !~ /JUnitTclTest.java/) {
                    jsrcLineNumber = 0;
                    printf("\tJUnitTclTest.java \\\n");
                }
                print $0
            }
        } else {
            if ($0 !~ /JUNIT_JAR/) {
                print $0 "$(CLASSPATHSEPARATOR)$(JUNIT_JAR)$(CLASSPATHSEPARATOR)$(PTJACL_JAR)"
            } else {
                if ($0 !~ /PTJACL_JAR/) {
                     print $0 "$(CLASSPATHSEPARATOR)$(PTJACL_JAR)"
                } else {
                     print $0
                }
            }
        }
    }' $testDir/makefile > $tmpmakefile
    diff $testDir/makefile $tmpmakefile
    status=$?
    if [ $status == 1 ]; then
	#echo "Would copy"
	cp $tmpmakefile $testDir/makefile
    fi	
done