name: GitHub Actions Demo
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PTII: $GITHUB_WORKSPACE

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: configure
      run: ./configure
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
