#*
.#*
*/.#*
*/#*
,*
*/,*
*~
*.a
.classpath
*.epsi
.netscape
*.o
*.obj
*.psd
*.so
*.snapshot
*/#auto#*
*/NoName
RCS
SCCS
CVS
PtolemyServer.log
.svn
.cvsignore
*/TAGS
*/tags
adm
alljsimpletests.tcl
alljtests.tcl
ant
bin/ptcg.bat
bin/copernicus.bat
bin/copernicusjhdl.bat
bin/convertToLazy
bin/decompile.bat
bin/emachine.bat
bin/giottoc.bat
bin/histogram.bat
bin/jode.bat
bin/mescal.bat
bin/moml.bat
bin/obfuscate.bat
bin/ptcg
bin/ptjg
bin/ptexecute.bat
bin/ptjacl.bat
bin/ptjaclapp.bat
bin/ptolemy.bat
bin/ptinvoke
bin/ptplot.bat
bin/ptstartjini.bat
bin/pxgraph.bat
bin/soot.bat
bin/startjini.gui.bat
bin/tinic.bat
bin/tinicomm.bat
bin/tiniconverter.bat
bin/vergil.bat
bin/comm.policy
bin/makebat
bin/makebat.lnk
bin/startjini.gui
bin/ptinvoke
bin/copernicus
bin/copernicusjhdl
bin/decompile
bin/ptcg
bin/ptjini
bin/emachine
bin/giottoc
bin/histogram
bin/jode
bin/mescal
bin/moml
bin/momllib
bin/nc2moml
bin/obfuscate
bin/ptexecute
bin/ptjacl
bin/ptjaclapp
bin/ptplot
bin/ptolemy
bin/pxgraph
bin/ptstartjini
bin/soot
bin/tinic
bin/tinicomm
bin/tiniconverter
bin/ptmatlab.dll
brass
collections
com/microstar/xml/driver
com/microstar/xml/SAXDriver.*
config/*.class
config/*.jar
config.cache
config.log
config.status
diva/build.xml
doc/design/src
doc/design/html
doc/doccheck
doc/findbugs.xml
doc/findbugs.out
doc/findbugs.htm
doc/findbugsOut.xml
doc/img/PtolemyIISplash.psd
doc/ojdcheck.htm
doc/uml
doc/uml/*
doc/img/*.psd
hs_err_pid*
java.hprof.txt
jsdatabase
jni/launcher/launcher.exe
jni/launcher/launcher
jni/test/jni
junk
lib/cachedir
lib/javax.comm.properties
lib/kepler-configs.jar
lib/kepler-icons.jar
lib/ptolemy.jar
lib/ptolemy-doc.jar
lib/ptII.properties
lib/ptvr.jar
make.out
mems
mk/ptII.mk
nsmail
ptdb/config/database/testdata/log.*
ptdb/config/database/testdata/__db.*
ptdb/config/database/testdata/*.dbxml
ptjar_tmpdir
ptolemy/PtolemyII.ptml
ptolemy/actor/corba
ptolemy/actor/lib/Broadcast.java
ptolemy/actor/lib/gui/KeystrokeSensor.java
ptolemy/actor/lib/hoc/test/auto/ApplyFunction.xml
ptolemy/actor/lib/javasound/test/pitchshift
ptolemy/actor/lib/javasound/test/outfile.wav
ptolemy/actor/lib/jspaces
ptolemy/actor/lib/net/test_auto
ptolemy/actor/lib/opencv
ptolemy/actor/lib/python/demo/HelloWorld
ptolemy/actor/lib/python/demo/NotifyFailedTest
ptolemy/actor/lib/security/test/auto/foo.keystore
ptolemy/actor/lib/security/test/foo.keystore
ptolemy/actor/lib/test/auto/FileWriter1Output.txt
ptolemy/actor/lib/test/Const.txt
ptolemy/actor/lib/test/ReadFile1Output.txt
ptolemy/actor/xslt
ptolemy/apps
ptolemy/automata
ptolemy/build.xml
ptolemy/filter/*
ptolemy/filter
ptolemy/chic
ptolemy/com
ptolemy/configs/test/vergilConfigurationNoMatlab.xml
ptolemy/configs/test/vergilConfigurationNoMatlabNoSerialNoApps.xml
ptolemy/configs/visualnc
ptolemy/data/expr/TVariable.java
ptolemy/gui/JPanelTest.java
ptolemy/codgen/c/domains/ptides
ptolemy/codegen/c/targets/arduino
ptolemy/codegen/c/targets/iRobot
ptolemy/codegen/c/targets/luminary
ptolemy/codegen/c/targets/pret
ptolemy/codegen/c/targets/win32
ptolemy/codegen/domains/sr
ptolemy/copernicus/actor/test/codeGenerator.tmp
ptolemy/copernicus/applet/test/ptII
ptolemy/copernicus/applet/test/tmp
ptolemy/copernicus/*/cg
ptolemy/copernicus/c/test/HashSetTest
ptolemy/copernicus/c/test/j2c_lib
ptolemy/copernicus/c/test/java.lang.Object.c
ptolemy/copernicus/c/test/java.lang.Object.h
ptolemy/copernicus/c/test/natives
ptolemy/copernicus/c/test/testOutput
ptolemy/copernicus/deep
ptolemy/copernicus/kernel/fragment
ptolemy/copernicus/interpreted/test/codeGenerator.tmp
ptolemy/copernicus/java/test/codeGenerator.tmp
ptolemy/copernicus/java/test/longjtests.tcl
ptolemy/copernicus/java/test/ptolemy*
ptolemy/copernicus/java/test/NamedObjConstructorAnalysis.class
ptolemy/copernicus/java/test/NamedObjConstructorAnalysis.java
ptolemy/copernicus/java/test/runSnapShot.stats
ptolemy/copernicus/jhdl
ptolemy/copernicus/shallow/test/codeGenerator.tmp
ptolemy/copernicus/shallow/ptolemy.giotto
ptolemy/domains/cont
ptolemy/domains/csp/demo/DiningPhilosophers/checkDeadlock
ptolemy/domains/ct/demo/Agilent
ptolemy/domains/ct/demo/Saber
ptolemy/domains/ct/demo/Corba
ptolemy/domains/ct/demo/SigmaDelta/DEStatistics.java
ptolemy/domains/ct/lib/IPCInterface.class
ptolemy/domains/ct/lib/IPCInterface.java
ptolemy/domains/dde/kernel/test/DDEDirector.tcl
ptolemy/domains/dde/kernel/test/test.tcl
ptolemy/domains/dde/kernel/DEThreadActor.java
ptolemy/domains/de/kernel/DEEDirector.java
ptolemy/domains/de/kernel/DETheadActor.java
ptolemy/domains/dt/kernel/test/bugs
ptolemy/domains/dt/kernel/test/chf
ptolemy/domains/dfm
ptolemy/domains/fairdf
ptolemy/domains/fsm/demo/Hysteresis
ptolemy/domains/generic
ptolemy/domains/giotto/demo/Helicopter
ptolemy/domains/giotto/demo/Legiotto
ptolemy/domains/giotto/kernel/test/ptolemy.giotto
ptolemy/domains/gr/lib/Loader3D.java
ptolemy/domains/gr/lib/Loader3D.class
ptolemy/domains/gr/lib/experimental
ptolemy/domains/gro
ptolemy/domains/hs
ptolemy/domains/nc
ptolemy/domains/odf
ptolemy/domains/pbo
ptolemy/domains/pdf
ptolemy/domains/rtos
ptolemy/domains/rtp
ptolemy/domains/sc
ptolemy/domains/sdf/codegen
ptolemy/domains/sdf/demo/FixPointSystem
ptolemy/domains/sdf/lib/huffman
ptolemy/domains/sdf/lib/javasound
ptolemy/domains/sdf/test/pitchshift
ptolemy/domains/tm/lib/PeriodicTrigger.java
ptolemy/domains/tm/runtime
ptolemy/domains/wireless/lib/network
ptolemy/domains/wireless/lib/tinyOS
ptolemy/domains/wireless/demo/MACProtocolModel
ptolemy/domains/wireless/demo/Network
ptolemy/domains/wireless/demo/network
ptolemy/kernel/test/TestSerializable.data
ptolemy/kernel/util/LibraryMarkerAttribute.java
ptolemy/kernel/util/UserSettable.java
ptolemy/lib/cachedir
ptolemy/lib/chic.jar
ptolemy/math/filter
ptolemy/matlab/ptmatlab.h
ptolemy/matlab/matlabLinux.jar
ptolemy/media/AudioQueue.java
ptolemy/media/ByteArrayAudioQueue.java
ptolemy/media/DoubleArrayAudioQueue.java
ptolemy/media/SoundCapture.java
ptolemy/media/SoundCapture.class
ptolemy/media/javasound/demo/LiveSines
ptolemy/media/javasound/demo/livesines
ptolemy/media/test/array.au
ptolemy/media/test/tmp2.au
ptolemy/media/test/tmp2*.au
ptolemy/moml/filter/test/compat
ptolemy/moml/filter/test/compat1
ptolemy/moml/filter/test/compat2
ptolemy/moml/filter/test/compat3
ptolemy/moml/filter/test/compat4
ptolemy/moml/filter/test/compatDemo
ptolemy/moml/filter/test/compatDemo1
ptolemy/moml/filter/test/compatDemo2
ptolemy/moml/filter/test/compatDemo3
ptolemy/moml/filter/test/compatDemo4
ptolemy/plot/adm
ptolemy/plot/build.xml
ptolemy/plot/Render
ptolemy/plot/RenderApplication.*
ptolemy/plotml/build.xml
ptolemy/schematic
ptolemy/system
ptolemy/util/test/FileUtilities-1.1.tmp
ptolemy/vergil/JModelViewer.java
ptolemy/vergil/debugger/demo2
ptolemy/vergil/graph
ptolemy/vergil/test/vergilConfigurationNoMatlabNoSerialNoApps.xml
ptolemy/verification/SystemGeneratedTempFolder*
ptolemy/verification/demo/SimpleTrafficLight/stl.kripke
ptserver/test/junit/PtolemyServer.log
replay_pid*.log
updateMoMLFiles.xml
vendors/jogl
vendors/jsdoc
socket.cfg
devel
htmlchek*
fmfilesvisited
