#!/bin/sh
# $Id: updateversions 47965 2008-01-26 17:29:50Z cxh $
# Update the versions of various files
# Usage updateversions oldVersion newVersion files . . .

oldVersion=$1
newVersion=$2
shift;shift
tmpfile=/tmp/updateversions.$$

for file in $@
do
    if [ -f $file ]; then
        case $file in
	    *.gif|*.jpg|*.png)	
		  echo "$0: file is a binary file."
		  ;;
	    *)
		sed "s/$oldVersion/$newVersion/g" $file > $tmpfile
		echo "$0: $file"
		diff $file $tmpfile
		mv $tmpfile $file
		;;
        esac
    else
	echo "$0: $file is not a file, perhaps it is a directory."
    fi
done
rm -f $tmpfile
